In [1]:
!pip install python-dotenv
!pip install matplotlib
#!pip install plotly==5.23.0
#!pip install -i https://test.pypi.org/simple/ dmtools-brown-edu --upgrade

Requirement already satisfied: python-dotenv in /usr/local/lib/python3.13/dist-packages (1.2.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
import sys
import os

# 1. Clear out any broken reference from Python's memory cache
if 'plot_functions' in sys.modules:
    del sys.modules['plot_functions']

# 2. Delete any existing copies of the file to start completely fresh
!rm -f plot_functions.py*

# 3. Download it again (Double-check that this URL is exactly correct!)
!wget https://raw.githubusercontent.com/BrownParticleAstro/dmtools_notebooks/refs/heads/main/libraries/plot_functions.py

# 4. Attempt a clean import
import plot_functions
print("Import successful!")

--2026-10-14 13:15:35--  https://raw.githubusercontent.com/BrownParticleAstro/dmtools_notebooks/refs/heads/main/libraries/plot_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12251 (12K) [text/plain]
Saving to: ‘plot_functions.py’

plot_functions.py   100%[===================>]  11.96K  --.-KB/s    in 0.002s

2026-10-14 13:15:36 (6.24 MB/s) - ‘plot_functions.py’ saved [12251/12251]

Import successful!

In [3]:
from plot_functions import get_color_mpl
from plot_functions import get_style_mpl
from plot_functions import get_clean_color_style
from plot_functions import get_empty_plot
from plot_functions import get_x_label
from plot_functions import convert_mass_units

In [4]:
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import io
import json
import os
import base64
from dotenv import load_dotenv
from typing import Dict, Any, Tuple, Callable, Optional
## only for local testing
from IPython.display import HTML, display

In [5]:
# for plotting
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import gridspec

# for legend
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
import numpy as np
from matplotlib.ticker import LogLocator, LogFormatterMathtext
from matplotlib.ticker import MultipleLocator

# for axes
from matplotlib.ticker import LogFormatterMathtext

### Load in some sample data that uses the existing dmtools JSON formatting

In [36]:
# @title
r_51 = [{'properties': {'comment': 'Sigma normalized to WIMP-Nucleon, no background subtraction',
   'dateAnnouncement': '1999-01-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'dash',
   'experiment': 'CDMS I (SUF)',
   'greatestHit': 0,
   'label': 'CDMS 1999 4 kg-day Ge',
   'label_short': 'CDMS 1999 4 kg-day Ge',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 90,
   'raw': '{[6.3095734 1.8632413e-37;8.1347616 2.6429088e-39;10.487927 1.807643e-40;13.521799 3.3370489e-41;17.433288 1.2176643e-41;22.476265 7.1061293e-42;28.978037 5.7609944e-42;37.360596 5.6309457e-42;48.168001 6.1214702e-42;62.101694 7.0796666e-42;80.066026 8.5454071e-42;103.22695 1.0551458e-41;133.0877 1.3144547e-41;171.58636 1.6630495e-41;221.22163 2.1110566e-41;285.21503 2.6923299e-41;367.71999 3.4462025e-41;474.09139 4.4171161e-41;611.23315 5.6721956e-41;788.04628 7.2906839e-41;1016.0067 9.3732685e-41;1309.9098 1.2064576e-40;1688.8311 1.5533328e-40;2177.364 2.0006402e-40;2807.2162 2.5772204e-40;3619.2676 3.3208156e-40;4666.2233 4.2792355e-40;6016.0349 5.5150189e-40;7756.3103 7.1082432e-40;10000 9.1626734e-40]}',
   'reference': 'Released TAUP Sept 1999 Conference: CDMS Contact Richard Schnee, schnee@casino.phys.cwru.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': [[['6.30957e+00', '1.86324e-37'],
     ['8.13476e+00', '2.64291e-39'],
     ['1.04879e+01', '1.80764e-40'],
     ['1.35218e+01', '3.33705e-41'],
     ['1.74333e+01', '1.21766e-41'],
     ['2.24763e+01', '7.10613e-42'],
     ['2.89780e+01', '5.76099e-42'],
     ['3.73606e+01', '5.63095e-42'],
     ['4.81680e+01', '6.12147e-42'],
     ['6.21017e+01', '7.07967e-42'],
     ['8.00660e+01', '8.54541e-42'],
     ['1.03227e+02', '1.05515e-41'],
     ['1.33088e+02', '1.31445e-41'],
     ['1.71586e+02', '1.66305e-41'],
     ['2.21222e+02', '2.11106e-41'],
     ['2.85215e+02', '2.69233e-41'],
     ['3.67720e+02', '3.44620e-41'],
     ['4.74091e+02', '4.41712e-41'],
     ['6.11233e+02', '5.67220e-41'],
     ['7.88046e+02', '7.29068e-41'],
     ['1.01601e+03', '9.37327e-41'],
     ['1.30991e+03', '1.20646e-40'],
     ['1.68883e+03', '1.55333e-40'],
     ['2.17736e+03', '2.00064e-40'],
     ['2.80722e+03', '2.57722e-40'],
     ['3.61927e+03', '3.32082e-40'],
     ['4.66622e+03', '4.27924e-40'],
     ['6.01603e+03', '5.51502e-40'],
     ['7.75631e+03', '7.10824e-40'],
     ['1.00000e+04', '9.16267e-40']]],
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 1999},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 51,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

In [ ]:
# @title
r_52 = [{'properties': {'comment': 'Sigma normalized to WIMP-Nucleon, Background subtracted',
   'dateAnnouncement': '1999-01-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': 'CDMS I (SUF)',
   'greatestHit': 0,
   'label': 'CDMS 1999 4 kg-day Ge with neutron bg subtract.',
   'label_short': 'CDMS 1999 4 kg-day Ge with neutron bg subtract.',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{[6.3095734 1.8228551e-37;8.1347616 2.5855165e-39;10.487927 1.7657822e-40;13.521799 3.2271517e-41;17.433288 1.1331211e-41;22.476265 6.2303537e-42;28.978037 4.7098555e-42;37.360596 4.3225733e-42;48.168001 4.53597e-42;62.101694 5.2108423e-42;80.066026 6.1999942e-42;103.22695 7.8027863e-42;133.0877 9.5350325e-42;171.58636 1.2032764e-41;221.22163 1.5279808e-41;285.21503 1.951882e-41;367.71999 2.4957172e-41;474.09139 3.2035739e-41;611.23315 4.1142131e-41;788.04628 5.2880028e-41;1016.0067 6.8038706e-41;1309.9098 8.7569666e-41;1688.8311 1.1276481e-40;2177.364 1.4523262e-40;2807.2162 1.8710993e-40;3619.2676 2.4110061e-40;4666.2233 3.10708e-40;6016.0349 4.0046148e-40;7756.3103 5.1614081e-40;10000 6.6534265e-40]}',
   'reference': 'Released TAUP Sept 1999 Conference: CDMS Contact Richard Schnee, schnee@casino.phys.cwru.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': [[['6.30957e+00', '1.82286e-37'],
     ['8.13476e+00', '2.58552e-39'],
     ['1.04879e+01', '1.76578e-40'],
     ['1.35218e+01', '3.22715e-41'],
     ['1.74333e+01', '1.13312e-41'],
     ['2.24763e+01', '6.23035e-42'],
     ['2.89780e+01', '4.70986e-42'],
     ['3.73606e+01', '4.32257e-42'],
     ['4.81680e+01', '4.53597e-42'],
     ['6.21017e+01', '5.21084e-42'],
     ['8.00660e+01', '6.19999e-42'],
     ['1.03227e+02', '7.80279e-42'],
     ['1.33088e+02', '9.53503e-42'],
     ['1.71586e+02', '1.20328e-41'],
     ['2.21222e+02', '1.52798e-41'],
     ['2.85215e+02', '1.95188e-41'],
     ['3.67720e+02', '2.49572e-41'],
     ['4.74091e+02', '3.20357e-41'],
     ['6.11233e+02', '4.11421e-41'],
     ['7.88046e+02', '5.28800e-41'],
     ['1.01601e+03', '6.80387e-41'],
     ['1.30991e+03', '8.75697e-41'],
     ['1.68883e+03', '1.12765e-40'],
     ['2.17736e+03', '1.45233e-40'],
     ['2.80722e+03', '1.87110e-40'],
     ['3.61927e+03', '2.41101e-40'],
     ['4.66622e+03', '3.10708e-40'],
     ['6.01603e+03', '4.00461e-40'],
     ['7.75631e+03', '5.16141e-40'],
     ['1.00000e+04', '6.65343e-40']]],
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 1999},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 52,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

In [66]:

def get_current_plots_data(datasets):

    plot_framework = get_empty_plot()
    plot_framework['dmtools_current_plot']['plot_node']['properties']['xUnits'] = 'GeV/c^2'
    plot_framework['dmtools_current_plot']['plot_node']['properties']['yMax'] = -44
    plot_framework['dmtools_current_plot']['plot_node']['properties']['yMin'] = -49
    plot_framework['dmtools_current_plot']['plot_node']['properties']['xMax'] = 10000
    plot_framework['dmtools_current_plot']['plot_node']['properties']['xMin'] = 8
    plot_framework['dmtools_current_plot']['plot_node']['properties']['name'] = "Plot Example"

    data_list = plot_framework['dmtools_current_plot']['display_data'][0]['data']

    # Clear the existing entries
    data_list.clear()

    for i in range(len(datasets)):
      record = datasets[i][0]['record']
      properties = datasets[i][0]['properties']
      data_list.append({
          'record': record,
          'properties': properties
      })

    json_data = plot_framework

    return json_data

### Adding the new data
- First block contains data from the 2025 LZ paper (The WS2024 dataset)
- Second block contains data from the 2026 LZ paper (The WS2025 dataset)
- Third and fourth blocks just place those values into the proper json format (note that some of the desrciptive fields aren't properly filled in for the sake of this exercise)

In [58]:
# @title
values2025 = [
    [
        [
            "9.0",
            "9.797484060822151e-47"
        ],
        [
            "11.0",
            "2.6404553011944104e-47"
        ],
        [
            "13.0",
            "1.2143606153767551e-47"
        ],
        [
            "16.0",
            "5.856844288044662e-48"
        ],
        [
            "17.0",
            "5.045161843317137e-48"
        ],
        [
            "19.0",
            "3.919409267394542e-48"
        ],
        [
            "21.0",
            "3.264671412324803e-48"
        ],
        [
            "23.0",
            "2.910809973414534e-48"
        ],
        [
            "26.0",
            "2.5810717410182406e-48"
        ],
        [
            "29.0",
            "2.4277055125156674e-48"
        ],
        [
            "32.0",
            "2.2931217929082963e-48"
        ],
        [
            "36.0",
            "2.2122904331621182e-48"
        ],
        [
            "40.0",
            "2.1816833824484827e-48"
        ],
        [
            "43.0",
            "2.217871458662707e-48"
        ],
        [
            "46.0",
            "2.2681993499922688e-48"
        ],
        [
            "65.0",
            "2.546041480288214e-48"
        ],
        [
            "91.0",
            "3.214860921122965e-48"
        ],
        [
            "129.0",
            "4.208919881771564e-48"
        ],
        [
            "182.0",
            "5.533572054224652e-48"
        ],
        [
            "256.0",
            "8.153750896244134e-48"
        ],
        [
            "361.0",
            "1.0969733548583377e-47"
        ],
        [
            "508.0",
            "1.546307933183269e-47"
        ],
        [
            "1008.0",
            "3.056000501431157e-47"
        ],
        [
            "2000.0",
            "5.732895978980354e-47"
        ],
        [
            "5000.0",
            "1.4448421055253768e-46"
        ],
        [
            "10000.0",
            "2.93003225261514e-46"
        ]
    ],
    [
        [
            "9.0",
            "6.360172460365096e-47"
        ],
        [
            "11.0",
            "1.8701390104493043e-47"
        ],
        [
            "13.0",
            "7.865482270647447e-48"
        ],
        [
            "16.0",
            "4.048247623143398e-48"
        ],
        [
            "17.0",
            "3.380911324758511e-48"
        ],
        [
            "19.0",
            "2.4860846835481487e-48"
        ],
        [
            "21.0",
            "1.97405947980569e-48"
        ],
        [
            "23.0",
            "1.6875655008991387e-48"
        ],
        [
            "26.0",
            "1.40693648954944e-48"
        ],
        [
            "29.0",
            "1.2768077708783247e-48"
        ],
        [
            "32.0",
            "1.2578359159028432e-48"
        ],
        [
            "36.0",
            "1.2048026298661685e-48"
        ],
        [
            "40.0",
            "1.2241600842374894e-48"
        ],
        [
            "43.0",
            "1.2677965776635033e-48"
        ],
        [
            "46.0",
            "1.319606104386345e-48"
        ],
        [
            "65.0",
            "1.8083215589752695e-48"
        ],
        [
            "91.0",
            "2.4014647187226817e-48"
        ],
        [
            "129.0",
            "3.493040099638599e-48"
        ],
        [
            "182.0",
            "4.819135224075079e-48"
        ],
        [
            "256.0",
            "7.251921401221729e-48"
        ],
        [
            "361.0",
            "9.787025883789508e-48"
        ],
        [
            "508.0",
            "1.4317111324481653e-47"
        ],
        [
            "1008.0",
            "2.786092050287613e-47"
        ],
        [
            "2000.0",
            "5.38102575807705e-47"
        ],
        [
            "5000.0",
            "1.3370021192602822e-46"
        ],
        [
            "10000.0",
            "2.7701300636845517e-46"
        ]
    ],
    [
        [
            "9.0",
            "6.048606167873016e-47"
        ],
        [
            "11.0",
            "1.4668916521102063e-47"
        ],
        [
            "13.0",
            "6.349722880519739e-48"
        ],
        [
            "16.0",
            "2.939552273941582e-48"
        ],
        [
            "17.0",
            "2.372342435271395e-48"
        ],
        [
            "19.0",
            "1.9579085670265272e-48"
        ],
        [
            "21.0",
            "1.6446642309537584e-48"
        ],
        [
            "23.0",
            "1.388198086098923e-48"
        ],
        [
            "26.0",
            "1.2895890381231673e-48"
        ],
        [
            "29.0",
            "1.1353477567166161e-48"
        ],
        [
            "32.0",
            "1.0791741586353313e-48"
        ],
        [
            "36.0",
            "1.0413430743896979e-48"
        ],
        [
            "40.0",
            "1.0343922912479032e-48"
        ],
        [
            "43.0",
            "1.0897886446843622e-48"
        ],
        [
            "46.0",
            "1.0570195945594763e-48"
        ],
        [
            "65.0",
            "1.2160842875189916e-48"
        ],
        [
            "91.0",
            "1.4867353834743516e-48"
        ],
        [
            "129.0",
            "1.9107273186768406e-48"
        ],
        [
            "182.0",
            "2.549350955580449e-48"
        ],
        [
            "256.0",
            "3.4986914786089955e-48"
        ],
        [
            "361.0",
            "5.157222312027698e-48"
        ],
        [
            "508.0",
            "7.094219706875709e-48"
        ],
        [
            "1008.0",
            "1.3810780025559867e-47"
        ],
        [
            "2000.0",
            "2.7321027795671195e-47"
        ],
        [
            "5000.0",
            "6.697000339773429e-47"
        ],
        [
            "10000.0",
            "1.3362203439327053e-46"
        ]
    ],
    [
        [
            "9.0",
            "9.893442198122728e-47"
        ],
        [
            "11.0",
            "2.6918785823219344e-47"
        ],
        [
            "13.0",
            "1.2302559129454687e-47"
        ],
        [
            "16.0",
            "5.946384796102546e-48"
        ],
        [
            "17.0",
            "5.16035714366596e-48"
        ],
        [
            "19.0",
            "3.965616220973367e-48"
        ],
        [
            "21.0",
            "3.323728873181861e-48"
        ],
        [
            "23.0",
            "2.996213570149687e-48"
        ],
        [
            "26.0",
            "2.624831549595038e-48"
        ],
        [
            "29.0",
            "2.4562102316699348e-48"
        ],
        [
            "32.0",
            "2.3339009812270167e-48"
        ],
        [
            "36.0",
            "2.2666795304596937e-48"
        ],
        [
            "40.0",
            "2.2464867009769235e-48"
        ],
        [
            "43.0",
            "2.2483991280651468e-48"
        ],
        [
            "46.0",
            "2.3032285368214262e-48"
        ],
        [
            "65.0",
            "2.5816453787544615e-48"
        ],
        [
            "91.0",
            "3.309866160233171e-48"
        ],
        [
            "129.0",
            "4.313435146992405e-48"
        ],
        [
            "182.0",
            "5.654047138734876e-48"
        ],
        [
            "256.0",
            "8.249019845152288e-48"
        ],
        [
            "361.0",
            "1.128688959698872e-47"
        ],
        [
            "508.0",
            "1.575147654507888e-47"
        ],
        [
            "1008.0",
            "3.135231270709062e-47"
        ],
        [
            "2000.0",
            "5.937434002106777e-47"
        ],
        [
            "5000.0",
            "1.4782897375478288e-46"
        ],
        [
            "10000.0",
            "3.0008405080539785e-46"
        ]
    ],
    [
        [
            "9.0",
            "2.3145818978695027e-46"
        ],
        [
            "11.0",
            "6.086757004761322e-47"
        ],
        [
            "13.0",
            "2.828495679333201e-47"
        ],
        [
            "16.0",
            "1.40000267517354e-47"
        ],
        [
            "17.0",
            "1.1916648052774437e-47"
        ],
        [
            "19.0",
            "9.302541001003626e-48"
        ],
        [
            "21.0",
            "7.629776555527764e-48"
        ],
        [
            "23.0",
            "6.860081746103876e-48"
        ],
        [
            "26.0",
            "6.096427774422581e-48"
        ],
        [
            "29.0",
            "5.601755116021929e-48"
        ],
        [
            "32.0",
            "5.309316082917047e-48"
        ],
        [
            "36.0",
            "5.090681232958277e-48"
        ],
        [
            "40.0",
            "5.0587223537493065e-48"
        ],
        [
            "43.0",
            "5.055364644860216e-48"
        ],
        [
            "46.0",
            "5.1954036449868804e-48"
        ],
        [
            "65.0",
            "5.992802958751586e-48"
        ],
        [
            "91.0",
            "7.422458464315766e-48"
        ],
        [
            "129.0",
            "9.767779832306256e-48"
        ],
        [
            "182.0",
            "1.3198015721888574e-47"
        ],
        [
            "256.0",
            "1.8325636140177053e-47"
        ],
        [
            "361.0",
            "2.5026197499670055e-47"
        ],
        [
            "508.0",
            "3.458283462086202e-47"
        ],
        [
            "1008.0",
            "6.833958871618215e-47"
        ],
        [
            "2000.0",
            "1.3394627139951759e-46"
        ],
        [
            "5000.0",
            "3.3556730400544437e-46"
        ],
        [
            "10000.0",
            "6.683686263656167e-46"
        ]
    ],
    [
        [
            "9.0",
            "4.194714251898931e-46"
        ],
        [
            "11.0",
            "1.1040826054423953e-46"
        ],
        [
            "13.0",
            "4.924628262308908e-47"
        ],
        [
            "16.0",
            "2.4672118233111775e-47"
        ],
        [
            "17.0",
            "2.1087352871554742e-47"
        ],
        [
            "19.0",
            "1.6509184360336717e-47"
        ],
        [
            "21.0",
            "1.3745886244053102e-47"
        ],
        [
            "23.0",
            "1.208340705478538e-47"
        ],
        [
            "26.0",
            "1.064602898282829e-47"
        ],
        [
            "29.0",
            "9.912336962513661e-48"
        ],
        [
            "32.0",
            "9.460588314015946e-48"
        ],
        [
            "36.0",
            "9.27440911921791e-48"
        ],
        [
            "40.0",
            "8.987337280871959e-48"
        ],
        [
            "43.0",
            "9.188354660507748e-48"
        ],
        [
            "46.0",
            "9.28590178459593e-48"
        ],
        [
            "65.0",
            "1.0681313676739283e-47"
        ],
        [
            "91.0",
            "1.3172503783042412e-47"
        ],
        [
            "129.0",
            "1.7440438780969673e-47"
        ],
        [
            "182.0",
            "2.372815458103765e-47"
        ],
        [
            "256.0",
            "3.221795344715976e-47"
        ],
        [
            "361.0",
            "4.464177661067317e-47"
        ],
        [
            "508.0",
            "6.271633584988651e-47"
        ],
        [
            "1008.0",
            "1.2107487584832586e-46"
        ],
        [
            "2000.0",
            "2.4144311800237557e-46"
        ],
        [
            "5000.0",
            "6.086069411404099e-46"
        ],
        [
            "10000.0",
            "1.2159498899422127e-45"
        ]
    ],
    [
        [
            "9.0",
            "6.208987087138066e-46"
        ],
        [
            "11.0",
            "1.6262330084733883e-46"
        ],
        [
            "13.0",
            "7.376376970640113e-47"
        ],
        [
            "16.0",
            "3.7146785808211216e-47"
        ],
        [
            "17.0",
            "3.156239326479482e-47"
        ],
        [
            "19.0",
            "2.469739802410441e-47"
        ],
        [
            "21.0",
            "2.0579363976500567e-47"
        ],
        [
            "23.0",
            "1.8485837979688936e-47"
        ],
        [
            "26.0",
            "1.6309150887888171e-47"
        ],
        [
            "29.0",
            "1.4985345570517207e-47"
        ],
        [
            "32.0",
            "1.4255652332998049e-47"
        ],
        [
            "36.0",
            "1.3746957151160644e-47"
        ],
        [
            "40.0",
            "1.3853719064038475e-47"
        ],
        [
            "43.0",
            "1.3950160690853623e-47"
        ],
        [
            "46.0",
            "1.4029246977096138e-47"
        ],
        [
            "65.0",
            "1.6256543545704663e-47"
        ],
        [
            "91.0",
            "2.0170849900045724e-47"
        ],
        [
            "129.0",
            "2.6443911225181474e-47"
        ],
        [
            "182.0",
            "3.593638519780333e-47"
        ],
        [
            "256.0",
            "4.910927822407369e-47"
        ],
        [
            "361.0",
            "6.871267727900406e-47"
        ],
        [
            "508.0",
            "9.606846430394522e-47"
        ],
        [
            "1008.0",
            "1.874095488915199e-46"
        ],
        [
            "2000.0",
            "3.704861397809596e-46"
        ],
        [
            "5000.0",
            "9.227400695280647e-46"
        ],
        [
            "10000.0",
            "1.8488843634379313e-45"
        ]
    ],
    [
        [
            "9.0",
            "4.40806591887947e-46"
        ],
        [
            "11.0",
            "1.223210047579738e-46"
        ],
        [
            "13.0",
            "5.60645601807054e-47"
        ],
        [
            "16.0",
            "2.8047930866531153e-47"
        ],
        [
            "17.0",
            "2.403883883122198e-47"
        ],
        [
            "19.0",
            "1.8837459711105122e-47"
        ],
        [
            "21.0",
            "1.5897316772219757e-47"
        ],
        [
            "23.0",
            "1.4069556914646076e-47"
        ],
        [
            "26.0",
            "1.2305328218712188e-47"
        ],
        [
            "29.0",
            "1.148610127865671e-47"
        ],
        [
            "32.0",
            "1.0956105766300616e-47"
        ],
        [
            "36.0",
            "1.0714219400455744e-47"
        ],
        [
            "40.0",
            "1.0617376217763808e-47"
        ],
        [
            "43.0",
            "1.0642928750477521e-47"
        ],
        [
            "46.0",
            "1.0788381790948551e-47"
        ],
        [
            "65.0",
            "1.2387941905136282e-47"
        ],
        [
            "91.0",
            "1.5441766760162665e-47"
        ],
        [
            "129.0",
            "2.0515058467201082e-47"
        ],
        [
            "182.0",
            "2.7689176158123063e-47"
        ],
        [
            "256.0",
            "3.8191599823138155e-47"
        ],
        [
            "361.0",
            "5.272945272912351e-47"
        ],
        [
            "508.0",
            "7.368551894569787e-47"
        ],
        [
            "1008.0",
            "1.44399629947039e-46"
        ],
        [
            "2000.0",
            "2.8596906406277796e-46"
        ],
        [
            "5000.0",
            "7.082048951811102e-46"
        ],
        [
            "10000.0",
            "1.4217307671255365e-45"
        ]
    ]
]

In [53]:
# @title
values2026 = [
    [
        [
            "3.0",
            "2.109960836759407e-42"
        ],
        [
            "3.5",
            "2.5159925340876324e-43"
        ],
        [
            "4.0",
            "4.583811401349886e-44"
        ],
        [
            "4.5",
            "1.3539744178249226e-44"
        ],
        [
            "5.0",
            "4.606589133997426e-45"
        ],
        [
            "5.5",
            "1.883608251794532e-45"
        ],
        [
            "6.0",
            "9.358552235538168e-46"
        ],
        [
            "6.5",
            "5.7432996174877045e-46"
        ],
        [
            "7.0",
            "3.5743149586009706e-46"
        ],
        [
            "7.5",
            "2.4051823982504194e-46"
        ],
        [
            "8.0",
            "1.791701785874015e-46"
        ],
        [
            "8.5",
            "1.3665638319819067e-46"
        ],
        [
            "9.0",
            "1.1123992891974162e-46"
        ]
    ],
    [
        [
            "3.0",
            "1.5857276153574122e-43"
        ],
        [
            "3.5",
            "2.961473962763499e-44"
        ],
        [
            "4.0",
            "9.030171046401482e-45"
        ],
        [
            "4.5",
            "3.8201028203460597e-45"
        ],
        [
            "5.0",
            "1.8276993462928463e-45"
        ],
        [
            "5.5",
            "7.993308034437688e-46"
        ],
        [
            "6.0",
            "4.070176175983345e-46"
        ],
        [
            "6.5",
            "2.2360912583716193e-46"
        ],
        [
            "7.0",
            "1.3297494940889578e-46"
        ],
        [
            "7.5",
            "8.576249766752253e-47"
        ],
        [
            "8.0",
            "5.919150049316113e-47"
        ],
        [
            "8.5",
            "4.355482424859933e-47"
        ],
        [
            "9.0",
            "3.5545153657788057e-47"
        ]
    ],
    [
        [
            "3.0",
            "3.75183285789539e-43"
        ],
        [
            "3.5",
            "6.195242314635826e-44"
        ],
        [
            "4.0",
            "1.6580213122836224e-44"
        ],
        [
            "4.5",
            "6.480724765150235e-45"
        ],
        [
            "5.0",
            "2.7617406963019574e-45"
        ],
        [
            "5.5",
            "1.23884648948262e-45"
        ],
        [
            "6.0",
            "6.406724399407369e-46"
        ],
        [
            "6.5",
            "3.674620686619736e-46"
        ],
        [
            "7.0",
            "2.2700378126226022e-46"
        ],
        [
            "7.5",
            "1.4020048238261778e-46"
        ],
        [
            "8.0",
            "1.0469832138546877e-46"
        ],
        [
            "8.5",
            "8.142843188348978e-47"
        ],
        [
            "9.0",
            "6.181808119519941e-47"
        ]
    ],
    [
        [
            "3.0",
            "9.450276189295662e-43"
        ],
        [
            "3.5",
            "1.38126703662455e-43"
        ],
        [
            "4.0",
            "3.5410319679685686e-44"
        ],
        [
            "4.5",
            "1.2672858289604764e-44"
        ],
        [
            "5.0",
            "5.494260794023094e-45"
        ],
        [
            "5.5",
            "2.7076992740070816e-45"
        ],
        [
            "6.0",
            "1.3675868468576688e-45"
        ],
        [
            "6.5",
            "8.022314084141774e-46"
        ],
        [
            "7.0",
            "5.0675968214770796e-46"
        ],
        [
            "7.5",
            "3.498857566926504e-46"
        ],
        [
            "8.0",
            "2.416549820194114e-46"
        ],
        [
            "8.5",
            "1.8609278812034606e-46"
        ],
        [
            "9.0",
            "1.5097689096119403e-46"
        ]
    ],
    [
        [
            "3.0",
            "2.3321768297323883e-42"
        ],
        [
            "3.5",
            "3.2919626735397087e-43"
        ],
        [
            "4.0",
            "8.392649361261529e-44"
        ],
        [
            "4.5",
            "3.1173922219958027e-44"
        ],
        [
            "5.0",
            "1.3546237677354515e-44"
        ],
        [
            "5.5",
            "6.653544145789427e-45"
        ],
        [
            "6.0",
            "3.523833596149638e-45"
        ],
        [
            "6.5",
            "1.930509387310811e-45"
        ],
        [
            "7.0",
            "1.1390424503526062e-45"
        ],
        [
            "7.5",
            "7.447227947954323e-46"
        ],
        [
            "8.0",
            "5.254926364650317e-46"
        ],
        [
            "8.5",
            "3.8292978726222256e-46"
        ],
        [
            "9.0",
            "3.0655913172873984e-46"
        ]
    ],
    [
        [
            "3.0",
            "4.7837160277150214e-42"
        ],
        [
            "3.5",
            "6.1004128603945914e-43"
        ],
        [
            "4.0",
            "1.3750355122865932e-43"
        ],
        [
            "4.5",
            "5.331650992462544e-44"
        ],
        [
            "5.0",
            "2.448998679028974e-44"
        ],
        [
            "5.5",
            "1.1901866943510293e-44"
        ],
        [
            "6.0",
            "5.734749764748965e-45"
        ],
        [
            "6.5",
            "3.291634289475447e-45"
        ],
        [
            "7.0",
            "1.9036251337830848e-45"
        ],
        [
            "7.5",
            "1.2354860239318686e-45"
        ],
        [
            "8.0",
            "8.858425845483195e-46"
        ],
        [
            "8.5",
            "6.511487175182374e-46"
        ],
        [
            "9.0",
            "4.945244764825409e-46"
        ]
    ],
    [
        [
            "3.0",
            "5.3798457989627204e-42"
        ],
        [
            "3.5",
            "6.838584646257011e-43"
        ],
        [
            "4.0",
            "1.581132713640845e-43"
        ],
        [
            "4.5",
            "5.98362257919107e-44"
        ],
        [
            "5.0",
            "2.641710023241966e-44"
        ],
        [
            "5.5",
            "1.2923827982390215e-44"
        ],
        [
            "6.0",
            "6.493849833550785e-45"
        ],
        [
            "6.5",
            "3.4405107648461885e-45"
        ],
        [
            "7.0",
            "2.0301967003279202e-45"
        ],
        [
            "7.5",
            "1.2606466157952078e-45"
        ],
        [
            "8.0",
            "8.719629983278816e-46"
        ],
        [
            "8.5",
            "6.416710555516401e-46"
        ],
        [
            "9.0",
            "4.821840298092588e-46"
        ]
    ]
]

In [67]:
# @title
LZ_2026 = [{'properties': {'comment': 'sigma normalized to DM-Nucleon',
   'dateAnnouncement': '2026-07-17',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': 'LZ',
   'greatestHit': 0,
   'label': 'LZ 17 Jul 2026 WS2025',
   'label_short': 'LZ 17 Jul 2026',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{}',
   'reference': 'LZ Spokesperson richard_gaitskell@brown.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': values2026,
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 2026},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 52,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

In [68]:
# @title
LZ_2025 = [{'properties': {'comment': 'sigma normalized to DM-Nucleon',
   'dateAnnouncement': '2025-07-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': 'LZ',
   'greatestHit': 0,
   'label': 'LZ 1 Jul 2025 WS2024',
   'label_short': 'LZ 1 Jul 2025',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{}',
   'reference': 'LZ Spokesperson richard_gaitskell@brown.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': values2025,
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 2025},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 52,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

### Adding in the other new data
- XENONnT
- LZ2023
- LUX

In [14]:
import pandas as pd

In [16]:
XENONnT = pd.read_csv("/content/XENONnT_2023_WIMP_SI_arxiv.csv")

In [17]:
XENONnT.head()

,#mass,UL(constrained),UL(unconstrained),-2sig,-1sig,median,+1sig,+2sig
0,6.0,3.081000e-44,2.853000e-44,6.955000e-45,1.156000e-44,3.082000e-44,6.370000e-44,1.138000e-43
1,7.0,7.318000e-45,4.976000e-45,1.613000e-45,2.727000e-45,7.317000e-45,1.471000e-44,2.594000e-44
2,8.0,2.477000e-45,1.260000e-45,5.447000e-46,9.297000e-46,2.477000e-45,4.879000e-45,8.501000e-45
3,9.0,1.072000e-45,4.379000e-46,2.377000e-46,4.078000e-46,1.072000e-45,2.078000e-45,3.580000e-45
4,10.0,5.527000e-46,1.985000e-46,1.245000e-46,2.140000e-46,5.527000e-46,1.060000e-45,1.806000e-45

In [20]:
XENONnT.columns

Index(['#mass', 'ULc', ' UL(unconstrained)', ' -2sig', ' -1sig', ' median',
       ' +1sig', ' +2sig'],
      dtype='object')

In [21]:
XENONnT = XENONnT.rename(columns={"#mass": "mass"})

In [22]:
XENONnT.head()

,mass,ULc,UL(unconstrained),-2sig,-1sig,median,+1sig,+2sig
0,6.0,3.081000e-44,2.853000e-44,6.955000e-45,1.156000e-44,3.082000e-44,6.370000e-44,1.138000e-43
1,7.0,7.318000e-45,4.976000e-45,1.613000e-45,2.727000e-45,7.317000e-45,1.471000e-44,2.594000e-44
2,8.0,2.477000e-45,1.260000e-45,5.447000e-46,9.297000e-46,2.477000e-45,4.879000e-45,8.501000e-45
3,9.0,1.072000e-45,4.379000e-46,2.377000e-46,4.078000e-46,1.072000e-45,2.078000e-45,3.580000e-45
4,10.0,5.527000e-46,1.985000e-46,1.245000e-46,2.140000e-46,5.527000e-46,1.060000e-45,1.806000e-45

In [23]:
values = [[]]
for row in XENONnT.itertuples():
  l = [row.mass, row.ULc]
  values[0].append(l)

In [62]:
XenonNTData = [{'properties': {'comment': 'sigma normalized to DM-Nucleon',
   'dateAnnouncement': '2025-07-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': '',
   'greatestHit': 0,
   'label': 'XenonNT',
   'label_short': 'LZ 1 Jul 2025',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{}',
   'reference': 'XenonNT Spokesperson blah@school.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': values,
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 2025},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 58,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

In [26]:
# @title
valuesLZ2023 = [
    [
        [9.0, 3.88141e-46],
        [11.0, 1.05545e-46],
        [13.0, 4.40606e-47],
        [16.0, 2.28511e-47],
        [17.0, 1.88394e-47],
        [19.0, 1.55761e-47],
        [21.0, 1.31963e-47],
        [23.0, 1.15272e-47],
        [26.0, 1.01760e-47],
        [29.0, 9.53429e-48],
        [30.0, 9.37582e-48],
        [32.0, 9.27823e-48],
        [36.0, 9.16769e-48],
        [40.0, 9.49545e-48],
        [43.0, 1.02165e-47],
        [46.0, 1.13143e-47],
        [55.0, 1.43786e-47],
        [65.0, 1.76318e-47],
        [78.0, 2.19292e-47],
        [91.0, 2.53863e-47],
        [110.0, 3.03790e-47],
        [129.0, 3.64334e-47],
        [155.0, 4.47954e-47],
        [182.0, 5.15116e-47],
        [219.0, 6.34341e-47],
        [256.0, 7.36760e-47],
        [308.0, 8.85464e-47],
        [361.0, 1.01762e-46],
        [434.0, 1.24217e-46],
        [508.0, 1.46316e-46],
        [612.0, 1.77592e-46],
        [716.0, 2.00948e-46],
        [862.0, 2.42561e-46],
        [1008.0, 2.89452e-46],
        [1214.0, 3.48215e-46],
        [1420.0, 4.09394e-46],
        [1710.0, 4.86699e-46],
        [2000.0, 5.75993e-46],
        [5000.0, 1.45172e-45],
        [10000.0, 2.79882e-45]
    ]
]

In [27]:
# @title
LUXvals = [
    [
        [5.0, 2.57864e-42],
        [5.52604925753, 3.73831792376e-43],
        [6.10744407932, 8.635083692880001e-44],
        [6.75000736398, 2.84216851286e-44],
        [7.46017463641, 1.19523122621e-44],
        [8.24505850211, 5.95781477285e-45],
        [9.11251988276, 3.34432334181e-45],
        [10.0712467465, 2.0094789900999998e-45],
        [11.1308411211, 1.25299981456e-45],
        [12.3019152626, 8.37642328364e-46],
        [13.5961979406, 6.0585486397099995e-46],
        [15.026651907, 4.48509058883e-46],
        [16.6076037228, 3.39621746367e-46],
        [18.3548872443, 2.71387884921e-46],
        [20.2860022057, 2.27325122753e-46],
        [22.4202894853, 1.9480152764e-46],
        [24.7791248128, 1.6911710338099999e-46],
        [27.3861328548, 1.48750826074e-46],
        [30.2674238257, 1.32590361258e-46],
        [33.4518549919, 1.19797916751e-46],
        [36.9713196882, 1.09742627368e-46],
        [40.8610667425, 1.0426205417200001e-46],
        [45.1600535068, 1.0760481873699998e-46],
        [49.9113360303, 1.12030153826e-46],
        [55.1625002824, 1.17345516876e-46],
        [60.9661387458, 1.23563229653e-46],
        [67.3803771501, 1.3076316635400001e-46],
        [74.4694566244, 1.39039207431e-46],
        [82.3043770976, 1.4850020980199999e-46],
        [90.9636083902, 1.59271118389e-46],
        [100.533876121, 1.71494193821e-46],
        [111.111030299, 1.85330326738e-46],
        [122.801005298, 2.00960402158e-46],
        [135.72088083, 2.18586668224e-46],
        [150.000054548, 2.38434052086e-46],
        [165.781538013, 2.6075135174399998e-46],
        [183.223389009, 2.8581221632800003e-46],
        [202.500294559, 3.13915808751e-46],
        [223.80532048, 3.45387024072e-46],
        [247.351845013, 3.80576114978e-46],
        [273.375695897, 4.19857553116e-46],
        [302.137512267, 4.63627932896e-46],
        [333.925355067, 5.12302704286e-46],
        [369.057592088, 5.663115050789999e-46],
        [407.886086548, 6.26092070482e-46],
        [450.799721145, 6.9213601545299994e-46],
        [498.228292865, 7.65082433367e-46],
        [550.646817573, 8.45653030517e-46],
        [608.580287482, 9.34645771884e-46],
        [672.608929157, 1.03294309969e-45],
        [743.374014714, 1.14152106187e-45],
        [821.584284415, 1.26145945447e-45],
        [908.023044978, 1.39395309425e-45],
        [1003.5560147, 1.54032435153e-45],
        [1109.13999399, 1.7020375011199998e-45],
        [1225.83244805, 1.88071562886e-45],
        [1354.80209788, 2.0781573926800002e-45],
        [1497.34062542, 2.29635623762e-45],
        [1654.87561027, 2.5375221269399998e-45],
        [1828.98482749, 2.80410578489e-45],
        [2021.4120496, 3.09882575248e-45],
        [2234.08451116, 3.4246985956799996e-45],
        [2469.13221083, 3.7850726477699995e-45],
        [2728.90924408, 4.18366571556e-45],
        [3016.01738042, 4.62460723406e-45],
        [3333.33212116, 5.11248541504e-45],
        [3684.03149864, 5.6524000054e-45],
        [4071.62790555, 6.25002109637e-45],
        [4500.00327288, 6.91157474944e-45],
        [4973.44794899, 7.643751436539999e-45],
        [5496.70366918, 8.45386796442e-45],
        [6075.01104598, 9.349945089209999e-45],
        [6714.16205602, 1.03407655694e-44],
        [7420.55804891, 1.14359354288e-44],
        [8201.27385933, 1.2645948344700002e-44],
        [9064.12866422, 1.39822530209e-44],
        [10017.764295, 1.54573233392e-44],
        [11071.7317889, 1.7084731008599999e-44],
        [12236.5870463, 1.88792203464e-44],
        [13523.9965524, 2.08567847283e-44],
        [14946.8542214, 2.30347441396e-44],
        [16519.4105345, 2.5431823137399996e-44],
        [18257.4152638, 2.80682284059e-44],
        [20178.2752126, 3.09657255138e-44],
        [22301.2285513, 3.4148874098e-44],
        [24647.5374956, 3.76483454204e-44],
        [27240.7012555, 4.1499604980999995e-44],
        [30106.6913895, 4.57430145847e-44],
        [33274.2119199, 5.04246091756e-44],
        [36774.9868149, 5.55970087402e-44],
        [40644.0777168, 6.13204913206e-44],
        [44920.235098, 6.76642586901e-44],
        [49646.2863622, 7.47079330103e-44],
        [54869.5647782, 8.25433311155e-44],
        [60642.3835407, 9.127657335899999e-44],
        [67022.5597079, 1.01030596683e-43],
        [74073.9932623, 1.11948157375e-43],
        [81867.3070938, 1.24195428646e-43],
        [90480.5543163, 1.37966322722e-43],
        [100000.0, 1.53487697882e-43]
    ]
]

In [63]:
LZ2023data = [{'properties': {'comment': 'sigma normalized to DM-Nucleon',
   'dateAnnouncement': '2025-07-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': '',
   'greatestHit': 0,
   'label': 'XenonNT',
   'label_short': 'LZ 1 Jul 2025',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{}',
   'reference': 'XenonNT Spokesperson blah@school.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': valuesLZ2023,
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 2025},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 58,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

In [64]:
LUXdata = [{'properties': {'comment': 'sigma normalized to DM-Nucleon',
   'dateAnnouncement': '2025-07-01',
   'dateEnd': None,
   'dateOfficial': None,
   'dateStart': None,
   'defaultColor': 'blue',
   'defaultStyle': 'line',
   'experiment': '',
   'greatestHit': 0,
   'label': 'XenonNT',
   'label_short': 'LZ 1 Jul 2025',
   'measurementType': 'Dir',
   'official': 1,
   'open': 0,
   'public': 0,
   'rating': 80,
   'raw': '{}',
   'reference': 'XenonNT Spokesperson blah@school.edu',
   'resultType': 'Other',
   'spinDependency': 'SI',
   'values': LUXvals,
   'xRescale': '1',
   'xUnits': 'GeV',
   'yRescale': '1',
   'yUnits': 'cm^2',
   'year': 2025},
  'record': {'archived': None,
   'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
   'id': 58,
   'type': 'Data',
   'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}}]

### Add all the new data to a dmtools plot object

In [69]:
dataset_list = [LZ_2025, XenonNTData, LZ2023data, LUXdata]
plot_dataCURRENT = get_current_plots_data(dataset_list)
plot_dataCURRENT

{'dmtools_current_plot': {'plot_node': {'record': {'id': -1,
    'type': 'Plot',
    'created': '2025-07-26T14:46:37.430Z',
    'updated': '2025-07-26T14:46:37.430Z'},
   'properties': {'name': 'Plot Example',
    'xMax': 10000,
    'xMin': 8,
    'yMax': -44,
    'yMin': -49,
    'xUnits': 'GeV/c^2',
    'yUnits': 'cm^2',
    'plotType': 'Cross Section vs WIMP Mass'}},
  'display_data': [{'data': [{'record': {'archived': None,
       'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
       'id': 52,
       'type': 'Data',
       'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'},
      'properties': {'comment': 'sigma normalized to DM-Nucleon',
       'dateAnnouncement': '2025-07-01',
       'dateEnd': None,
       'dateOfficial': None,
       'dateStart': None,
       'defaultColor': 'blue',
       'defaultStyle': 'line',
       'experiment': 'LZ',
       'greatestHit': 0,
       'label': 'LZ 1 Jul 2025 WS2024',
       'label_short': 'LZ 1 Jul 2025',
       'measurementType': 'Dir',
       'official': 1,
       'open': 0,
       'public': 0,
       'rating': 80,
       'raw': '{}',
       'reference': 'LZ Spokesperson richard_gaitskell@brown.edu',
       'resultType': 'Other',
       'spinDependency': 'SI',
       'values': [[['9.0', '9.797484060822151e-47'],
         ['11.0', '2.6404553011944104e-47'],
         ['13.0', '1.2143606153767551e-47'],
         ['16.0', '5.856844288044662e-48'],
         ['17.0', '5.045161843317137e-48'],
         ['19.0', '3.919409267394542e-48'],
         ['21.0', '3.264671412324803e-48'],
         ['23.0', '2.910809973414534e-48'],
         ['26.0', '2.5810717410182406e-48'],
         ['29.0', '2.4277055125156674e-48'],
         ['32.0', '2.2931217929082963e-48'],
         ['36.0', '2.2122904331621182e-48'],
         ['40.0', '2.1816833824484827e-48'],
         ['43.0', '2.217871458662707e-48'],
         ['46.0', '2.2681993499922688e-48'],
         ['65.0', '2.546041480288214e-48'],
         ['91.0', '3.214860921122965e-48'],
         ['129.0', '4.208919881771564e-48'],
         ['182.0', '5.533572054224652e-48'],
         ['256.0', '8.153750896244134e-48'],
         ['361.0', '1.0969733548583377e-47'],
         ['508.0', '1.546307933183269e-47'],
         ['1008.0', '3.056000501431157e-47'],
         ['2000.0', '5.732895978980354e-47'],
         ['5000.0', '1.4448421055253768e-46'],
         ['10000.0', '2.93003225261514e-46']],
        [['9.0', '6.360172460365096e-47'],
         ['11.0', '1.8701390104493043e-47'],
         ['13.0', '7.865482270647447e-48'],
         ['16.0', '4.048247623143398e-48'],
         ['17.0', '3.380911324758511e-48'],
         ['19.0', '2.4860846835481487e-48'],
         ['21.0', '1.97405947980569e-48'],
         ['23.0', '1.6875655008991387e-48'],
         ['26.0', '1.40693648954944e-48'],
         ['29.0', '1.2768077708783247e-48'],
         ['32.0', '1.2578359159028432e-48'],
         ['36.0', '1.2048026298661685e-48'],
         ['40.0', '1.2241600842374894e-48'],
         ['43.0', '1.2677965776635033e-48'],
         ['46.0', '1.319606104386345e-48'],
         ['65.0', '1.8083215589752695e-48'],
         ['91.0', '2.4014647187226817e-48'],
         ['129.0', '3.493040099638599e-48'],
         ['182.0', '4.819135224075079e-48'],
         ['256.0', '7.251921401221729e-48'],
         ['361.0', '9.787025883789508e-48'],
         ['508.0', '1.4317111324481653e-47'],
         ['1008.0', '2.786092050287613e-47'],
         ['2000.0', '5.38102575807705e-47'],
         ['5000.0', '1.3370021192602822e-46'],
         ['10000.0', '2.7701300636845517e-46']],
        [['9.0', '6.048606167873016e-47'],
         ['11.0', '1.4668916521102063e-47'],
         ['13.0', '6.349722880519739e-48'],
         ['16.0', '2.939552273941582e-48'],
         ['17.0', '2.372342435271395e-48'],
         ['19.0', '1.9579085670265272e-48'],
         ['21.0', '1.6446642309537584e-48'],
         ['23.0', '1.388198086098923e-48'],
         ['26.0', '1.2895890381231673e-48'],
         ['29.0', '1.1353477567166161e-48'],
         ['32.0', '1.0791741586353313e-48'],
         ['36.0', '1.0413430743896979e-48'],
         ['40.0', '1.0343922912479032e-48'],
         ['43.0', '1.0897886446843622e-48'],
         ['46.0', '1.0570195945594763e-48'],
         ['65.0', '1.2160842875189916e-48'],
         ['91.0', '1.4867353834743516e-48'],
         ['129.0', '1.9107273186768406e-48'],
         ['182.0', '2.549350955580449e-48'],
         ['256.0', '3.4986914786089955e-48'],
         ['361.0', '5.157222312027698e-48'],
         ['508.0', '7.094219706875709e-48'],
         ['1008.0', '1.3810780025559867e-47'],
         ['2000.0', '2.7321027795671195e-47'],
         ['5000.0', '6.697000339773429e-47'],
         ['10000.0', '1.3362203439327053e-46']],
        [['9.0', '9.893442198122728e-47'],
         ['11.0', '2.6918785823219344e-47'],
         ['13.0', '1.2302559129454687e-47'],
         ['16.0', '5.946384796102546e-48'],
         ['17.0', '5.16035714366596e-48'],
         ['19.0', '3.965616220973367e-48'],
         ['21.0', '3.323728873181861e-48'],
         ['23.0', '2.996213570149687e-48'],
         ['26.0', '2.624831549595038e-48'],
         ['29.0', '2.4562102316699348e-48'],
         ['32.0', '2.3339009812270167e-48'],
         ['36.0', '2.2666795304596937e-48'],
         ['40.0', '2.2464867009769235e-48'],
         ['43.0', '2.2483991280651468e-48'],
         ['46.0', '2.3032285368214262e-48'],
         ['65.0', '2.5816453787544615e-48'],
         ['91.0', '3.309866160233171e-48'],
         ['129.0', '4.313435146992405e-48'],
         ['182.0', '5.654047138734876e-48'],
         ['256.0', '8.249019845152288e-48'],
         ['361.0', '1.128688959698872e-47'],
         ['508.0', '1.575147654507888e-47'],
         ['1008.0', '3.135231270709062e-47'],
         ['2000.0', '5.937434002106777e-47'],
         ['5000.0', '1.4782897375478288e-46'],
         ['10000.0', '3.0008405080539785e-46']],
        [['9.0', '2.3145818978695027e-46'],
         ['11.0', '6.086757004761322e-47'],
         ['13.0', '2.828495679333201e-47'],
         ['16.0', '1.40000267517354e-47'],
         ['17.0', '1.1916648052774437e-47'],
         ['19.0', '9.302541001003626e-48'],
         ['21.0', '7.629776555527764e-48'],
         ['23.0', '6.860081746103876e-48'],
         ['26.0', '6.096427774422581e-48'],
         ['29.0', '5.601755116021929e-48'],
         ['32.0', '5.309316082917047e-48'],
         ['36.0', '5.090681232958277e-48'],
         ['40.0', '5.0587223537493065e-48'],
         ['43.0', '5.055364644860216e-48'],
         ['46.0', '5.1954036449868804e-48'],
         ['65.0', '5.992802958751586e-48'],
         ['91.0', '7.422458464315766e-48'],
         ['129.0', '9.767779832306256e-48'],
         ['182.0', '1.3198015721888574e-47'],
         ['256.0', '1.8325636140177053e-47'],
         ['361.0', '2.5026197499670055e-47'],
         ['508.0', '3.458283462086202e-47'],
         ['1008.0', '6.833958871618215e-47'],
         ['2000.0', '1.3394627139951759e-46'],
         ['5000.0', '3.3556730400544437e-46'],
         ['10000.0', '6.683686263656167e-46']],
        [['9.0', '4.194714251898931e-46'],
         ['11.0', '1.1040826054423953e-46'],
         ['13.0', '4.924628262308908e-47'],
         ['16.0', '2.4672118233111775e-47'],
         ['17.0', '2.1087352871554742e-47'],
         ['19.0', '1.6509184360336717e-47'],
         ['21.0', '1.3745886244053102e-47'],
         ['23.0', '1.208340705478538e-47'],
         ['26.0', '1.064602898282829e-47'],
         ['29.0', '9.912336962513661e-48'],
         ['32.0', '9.460588314015946e-48'],
         ['36.0', '9.27440911921791e-48'],
         ['40.0', '8.987337280871959e-48'],
         ['43.0', '9.188354660507748e-48'],
         ['46.0', '9.28590178459593e-48'],
         ['65.0', '1.0681313676739283e-47'],
         ['91.0', '1.3172503783042412e-47'],
         ['129.0', '1.7440438780969673e-47'],
         ['182.0', '2.372815458103765e-47'],
         ['256.0', '3.221795344715976e-47'],
         ['361.0', '4.464177661067317e-47'],
         ['508.0', '6.271633584988651e-47'],
         ['1008.0', '1.2107487584832586e-46'],
         ['2000.0', '2.4144311800237557e-46'],
         ['5000.0', '6.086069411404099e-46'],
         ['10000.0', '1.2159498899422127e-45']],
        [['9.0', '6.208987087138066e-46'],
         ['11.0', '1.6262330084733883e-46'],
         ['13.0', '7.376376970640113e-47'],
         ['16.0', '3.7146785808211216e-47'],
         ['17.0', '3.156239326479482e-47'],
         ['19.0', '2.469739802410441e-47'],
         ['21.0', '2.0579363976500567e-47'],
         ['23.0', '1.8485837979688936e-47'],
         ['26.0', '1.6309150887888171e-47'],
         ['29.0', '1.4985345570517207e-47'],
         ['32.0', '1.4255652332998049e-47'],
         ['36.0', '1.3746957151160644e-47'],
         ['40.0', '1.3853719064038475e-47'],
         ['43.0', '1.3950160690853623e-47'],
         ['46.0', '1.4029246977096138e-47'],
         ['65.0', '1.6256543545704663e-47'],
         ['91.0', '2.0170849900045724e-47'],
         ['129.0', '2.6443911225181474e-47'],
         ['182.0', '3.593638519780333e-47'],
         ['256.0', '4.910927822407369e-47'],
         ['361.0', '6.871267727900406e-47'],
         ['508.0', '9.606846430394522e-47'],
         ['1008.0', '1.874095488915199e-46'],
         ['2000.0', '3.704861397809596e-46'],
         ['5000.0', '9.227400695280647e-46'],
         ['10000.0', '1.8488843634379313e-45']],
        [['9.0', '4.40806591887947e-46'],
         ['11.0', '1.223210047579738e-46'],
         ['13.0', '5.60645601807054e-47'],
         ['16.0', '2.8047930866531153e-47'],
         ['17.0', '2.403883883122198e-47'],
         ['19.0', '1.8837459711105122e-47'],
         ['21.0', '1.5897316772219757e-47'],
         ['23.0', '1.4069556914646076e-47'],
         ['26.0', '1.2305328218712188e-47'],
         ['29.0', '1.148610127865671e-47'],
         ['32.0', '1.0956105766300616e-47'],
         ['36.0', '1.0714219400455744e-47'],
         ['40.0', '1.0617376217763808e-47'],
         ['43.0', '1.0642928750477521e-47'],
         ['46.0', '1.0788381790948551e-47'],
         ['65.0', '1.2387941905136282e-47'],
         ['91.0', '1.5441766760162665e-47'],
         ['129.0', '2.0515058467201082e-47'],
         ['182.0', '2.7689176158123063e-47'],
         ['256.0', '3.8191599823138155e-47'],
         ['361.0', '5.272945272912351e-47'],
         ['508.0', '7.368551894569787e-47'],
         ['1008.0', '1.44399629947039e-46'],
         ['2000.0', '2.8596906406277796e-46'],
         ['5000.0', '7.082048951811102e-46'],
         ['10000.0', '1.4217307671255365e-45']]],
       'xRescale': '1',
       'xUnits': 'GeV',
       'yRescale': '1',
       'yUnits': 'cm^2',
       'year': 2025}},
     {'record': {'archived': None,
       'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
       'id': 58,
       'type': 'Data',
       'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'},
      'properties': {'comment': 'sigma normalized to DM-Nucleon',
       'dateAnnouncement': '2025-07-01',
       'dateEnd': None,
       'dateOfficial': None,
       'dateStart': None,
       'defaultColor': 'blue',
       'defaultStyle': 'line',
       'experiment': '',
       'greatestHit': 0,
       'label': 'XenonNT',
       'label_short': 'LZ 1 Jul 2025',
       'measurementType': 'Dir',
       'official': 1,
       'open': 0,
       'public': 0,
       'rating': 80,
       'raw': '{}',
       'reference': 'XenonNT Spokesperson blah@school.edu',
       'resultType': 'Other',
       'spinDependency': 'SI',
       'values': [[[6.0, 3.081e-44],
         [7.0, 7.318e-45],
         [8.0, 2.4769999999999997e-45],
         [9.0, 1.072e-45],
         [10.0, 5.5270000000000005e-46],
         [11.0, 3.248e-46],
         [12.0, 2.1080000000000002e-46],
         [13.0, 1.477e-46],
         [15.0, 8.594999999999999e-47],
         [17.0, 5.865999999999999e-47],
         [20.0, 4.0049999999999996e-47],
         [23.0, 3.16e-47],
         [25.0, 2.838e-47],
         [26.0, 2.719e-47],
         [28.14, 2.587e-47],
         [30.0, 2.6159999999999996e-47],
         [35.0, 2.761e-47],
         [40.0, 2.9600000000000003e-47],
         [45.0, 3.188e-47],
         [50.0, 3.431e-47],
         [55.0, 3.683e-47],
         [60.0, 3.939e-47],
         [70.0, 4.458e-47],
         [75.0, 4.722e-47],
         [80.0, 4.987999999999999e-47],
         [90.0, 5.527e-47],
         [100.0, 6.074e-47],
         [125.0, 7.468e-47],
         [150.0, 8.887e-47],
         [200.0, 1.1760000000000002e-46],
         [500.0, 2.8570000000000003e-46],
         [1000.0, 5.6360000000000005e-46],
         [10000.0, 5.635999999999999e-45]]],
       'xRescale': '1',
       'xUnits': 'GeV',
       'yRescale': '1',
       'yUnits': 'cm^2',
       'year': 2025}},
     {'record': {'archived': None,
       'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
       'id': 58,
       'type': 'Data',
       'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'},
      'properties': {'comment': 'sigma normalized to DM-Nucleon',
       'dateAnnouncement': '2025-07-01',
       'dateEnd': None,
       'dateOfficial': None,
       'dateStart': None,
       'defaultColor': 'blue',
       'defaultStyle': 'line',
       'experiment': '',
       'greatestHit': 0,
       'label': 'XenonNT',
       'label_short': 'LZ 1 Jul 2025',
       'measurementType': 'Dir',
       'official': 1,
       'open': 0,
       'public': 0,
       'rating': 80,
       'raw': '{}',
       'reference': 'XenonNT Spokesperson blah@school.edu',
       'resultType': 'Other',
       'spinDependency': 'SI',
       'values': [[[9.0, 3.88141e-46],
         [11.0, 1.05545e-46],
         [13.0, 4.40606e-47],
         [16.0, 2.28511e-47],
         [17.0, 1.88394e-47],
         [19.0, 1.55761e-47],
         [21.0, 1.31963e-47],
         [23.0, 1.15272e-47],
         [26.0, 1.0176e-47],
         [29.0, 9.53429e-48],
         [30.0, 9.37582e-48],
         [32.0, 9.27823e-48],
         [36.0, 9.16769e-48],
         [40.0, 9.49545e-48],
         [43.0, 1.02165e-47],
         [46.0, 1.13143e-47],
         [55.0, 1.43786e-47],
         [65.0, 1.76318e-47],
         [78.0, 2.19292e-47],
         [91.0, 2.53863e-47],
         [110.0, 3.0379e-47],
         [129.0, 3.64334e-47],
         [155.0, 4.47954e-47],
         [182.0, 5.15116e-47],
         [219.0, 6.34341e-47],
         [256.0, 7.3676e-47],
         [308.0, 8.85464e-47],
         [361.0, 1.01762e-46],
         [434.0, 1.24217e-46],
         [508.0, 1.46316e-46],
         [612.0, 1.77592e-46],
         [716.0, 2.00948e-46],
         [862.0, 2.42561e-46],
         [1008.0, 2.89452e-46],
         [1214.0, 3.48215e-46],
         [1420.0, 4.09394e-46],
         [1710.0, 4.86699e-46],
         [2000.0, 5.75993e-46],
         [5000.0, 1.45172e-45],
         [10000.0, 2.79882e-45]]],
       'xRescale': '1',
       'xUnits': 'GeV',
       'yRescale': '1',
       'yUnits': 'cm^2',
       'year': 2025}},
     {'record': {'archived': None,
       'created': 'Tue, 21 Jan 2025 14:22:36 GMT',
       'id': 58,
       'type': 'Data',
       'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'},
      'properties': {'comment': 'sigma normalized to DM-Nucleon',
       'dateAnnouncement': '2025-07-01',
       'dateEnd': None,
       'dateOfficial': None,
       'dateStart': None,
       'defaultColor': 'blue',
       'defaultStyle': 'line',
       'experiment': '',
       'greatestHit': 0,
       'label': 'XenonNT',
       'label_short': 'LZ 1 Jul 2025',
       'measurementType': 'Dir',
       'official': 1,
       'open': 0,
       'public': 0,
       'rating': 80,
       'raw': '{}',
       'reference': 'XenonNT Spokesperson blah@school.edu',
       'resultType': 'Other',
       'spinDependency': 'SI',
       'values': [[[5.0, 2.57864e-42],
         [5.52604925753, 3.73831792376e-43],
         [6.10744407932, 8.635083692880001e-44],
         [6.75000736398, 2.84216851286e-44],
         [7.46017463641, 1.19523122621e-44],
         [8.24505850211, 5.95781477285e-45],
         [9.11251988276, 3.34432334181e-45],
         [10.0712467465, 2.0094789900999998e-45],
         [11.1308411211, 1.25299981456e-45],
         [12.3019152626, 8.37642328364e-46],
         [13.5961979406, 6.0585486397099995e-46],
         [15.026651907, 4.48509058883e-46],
         [16.6076037228, 3.39621746367e-46],
         [18.3548872443, 2.71387884921e-46],
         [20.2860022057, 2.27325122753e-46],
         [22.4202894853, 1.9480152764e-46],
         [24.7791248128, 1.6911710338099999e-46],
         [27.3861328548, 1.48750826074e-46],
         [30.2674238257, 1.32590361258e-46],
         [33.4518549919, 1.19797916751e-46],
         [36.9713196882, 1.09742627368e-46],
         [40.8610667425, 1.0426205417200001e-46],
         [45.1600535068, 1.0760481873699998e-46],
         [49.9113360303, 1.12030153826e-46],
         [55.1625002824, 1.17345516876e-46],
         [60.9661387458, 1.23563229653e-46],
         [67.3803771501, 1.3076316635400001e-46],
         [74.4694566244, 1.39039207431e-46],
         [82.3043770976, 1.4850020980199999e-46],
         [90.9636083902, 1.59271118389e-46],
         [100.533876121, 1.71494193821e-46],
         [111.111030299, 1.85330326738e-46],
         [122.801005298, 2.00960402158e-46],
         [135.72088083, 2.18586668224e-46],
         [150.000054548, 2.38434052086e-46],
         [165.781538013, 2.6075135174399998e-46],
         [183.223389009, 2.8581221632800003e-46],
         [202.500294559, 3.13915808751e-46],
         [223.80532048, 3.45387024072e-46],
         [247.351845013, 3.80576114978e-46],
         [273.375695897, 4.19857553116e-46],
         [302.137512267, 4.63627932896e-46],
         [333.925355067, 5.12302704286e-46],
         [369.057592088, 5.663115050789999e-46],
         [407.886086548, 6.26092070482e-46],
         [450.799721145, 6.9213601545299994e-46],
         [498.228292865, 7.65082433367e-46],
         [550.646817573, 8.45653030517e-46],
         [608.580287482, 9.34645771884e-46],
         [672.608929157, 1.03294309969e-45],
         [743.374014714, 1.14152106187e-45],
         [821.584284415, 1.26145945447e-45],
         [908.023044978, 1.39395309425e-45],
         [1003.5560147, 1.54032435153e-45],
         [1109.13999399, 1.7020375011199998e-45],
         [1225.83244805, 1.88071562886e-45],
         [1354.80209788, 2.0781573926800002e-45],
         [1497.34062542, 2.29635623762e-45],
         [1654.87561027, 2.5375221269399998e-45],
         [1828.98482749, 2.80410578489e-45],
         [2021.4120496, 3.09882575248e-45],
         [2234.08451116, 3.4246985956799996e-45],
         [2469.13221083, 3.7850726477699995e-45],
         [2728.90924408, 4.18366571556e-45],
         [3016.01738042, 4.62460723406e-45],
         [3333.33212116, 5.11248541504e-45],
         [3684.03149864, 5.6524000054e-45],
         [4071.62790555, 6.25002109637e-45],
         [4500.00327288, 6.91157474944e-45],
         [4973.44794899, 7.643751436539999e-45],
         [5496.70366918, 8.45386796442e-45],
         [6075.01104598, 9.349945089209999e-45],
         [6714.16205602, 1.03407655694e-44],
         [7420.55804891, 1.14359354288e-44],
         [8201.27385933, 1.2645948344700002e-44],
         [9064.12866422, 1.39822530209e-44],
         [10017.764295, 1.54573233392e-44],
         [11071.7317889, 1.7084731008599999e-44],
         [12236.5870463, 1.88792203464e-44],
         [13523.9965524, 2.08567847283e-44],
         [14946.8542214, 2.30347441396e-44],
         [16519.4105345, 2.5431823137399996e-44],
         [18257.4152638, 2.80682284059e-44],
         [20178.2752126, 3.09657255138e-44],
         [22301.2285513, 3.4148874098e-44],
         [24647.5374956, 3.76483454204e-44],
         [27240.7012555, 4.1499604980999995e-44],
         [30106.6913895, 4.57430145847e-44],
         [33274.2119199, 5.04246091756e-44],
         [36774.9868149, 5.55970087402e-44],
         [40644.0777168, 6.13204913206e-44],
         [44920.235098, 6.76642586901e-44],
         [49646.2863622, 7.47079330103e-44],

The kwargs_list below is not standard dmtools plot functionality. The reasoning I am using it is as follows: for this notebook I put all the lines for the LZ data (-2sigma, -1sigma, median, etc) in one data entry and for a single data entry only 1 style can be provided. Additionally, to make the plot look exactly like the one from the paper there were more kwargs I needed to supply then there is space for in the json (perhaps we could change default line and color to just a single kwargs entry in the json). For the final product this business will be resolved and there will be no need for this. Again, it was a temporary work around for when our approch to plotting datasets with multiple lines was unclear. order_list also can be ignored.

In [33]:
kwargs_list = [
    {'color': 'black', 'alpha': 1, 'linestyle': '-', 'linewidth': 2.5, 'marker': None, 'markersize': 0}, #limit
    {'color': 'grey', 'alpha': 1, 'linestyle': '-.', 'linewidth': 2, 'marker': None, 'markersize': 0}, #limit unconstrained
    {'color': '#FFF59D', 'alpha': 0.8}, #-2 sigma
    {'color': '#A5F56A', 'alpha': 1.0}, #-1 sigma
    {'color': 'black', 'alpha': 1, 'linestyle': '--', 'linewidth': 2.5, 'marker': None, 'markersize': 0}, #median
    {'color': 'green', 'alpha': 0.5}, #1 sigma
    {'color': 'yellow', 'alpha': 0.5}, #2 sigma
    {'color': 'black', 'alpha': 1, 'linestyle': ':', 'linewidth': 3, 'marker': None, 'markersize': 0}, #median 3 sigma disco
    {'color': '#4CAF50', 'alpha': 1, 'linestyle': '-', 'linewidth': 2.5, 'marker': None, 'markersize': 0}, #XENONnT
    {'color': '#B35CE0', 'alpha': 1, 'linestyle': '-', 'linewidth': 2.5, 'marker': None, 'markersize': 0}, #LZ2023
    {'color': '#DF7C7D', 'alpha': 1, 'linestyle': '-', 'linewidth': 2.5, 'marker': None, 'markersize': 0} #LUX
]

In [34]:
order_list = ["lim", "lim unc", "-2sig", "-1sig", "med", "1sig", "2sig", "3sig"]

In [71]:
def create_standard_figure():
    """Create a standard figure with consistent styling"""
    fig = plt.figure(figsize=(10, 7), linewidth=0, edgecolor='#FFFFFF', facecolor='#FFFFFF')
    gs = gridspec.GridSpec(64, 64)
    ax = fig.add_subplot(gs[2:63, 2:63])
    ax.set_facecolor('white')
    ax.tick_params(axis='both', which='major', direction='in', top=True, right=True, length=9, width=1.5, labelsize=16)
    ax.tick_params(axis='both', which='minor', direction='in', top=True, right=True, length=5, width=1.1)
    return fig, ax

def save_figure_to_base64(fig, format_in='svg', dpi=100):
    """Save a matplotlib figure to base64 encoded string"""
    img = io.BytesIO()
    fig.savefig(img, format=format_in, dpi=dpi, bbox_inches='tight', pad_inches=0.25)
    img.seek(0)
    plt.close(fig)  # Close the figure to free memory
    return base64.b64encode(img.getvalue()).decode('utf8')

def set_plot_data(function_mode="local", format_in='svg'):
    """
    Main function that delegates to specific plot functions based on plot type
    """
    # Get the data - either from local cache or from a connection
    if function_mode == "local":
        # data = get_current_plots_data(LZ_2025)
        # plot_data = data.get('dmtools_current_plot')
        plot_data = plot_dataCURRENT['dmtools_current_plot']

        print("plot_data>>>>>>>>>", plot_data)
    else:
        try:
            # This would be your remote data retrieval code
            plot_data = {}  # Placeholder
        except:
            plot_data = {}

    # Extract plot type and other key properties
    plot_node = plot_data.get("plot_node", {})
    plot_properties = plot_node.get("properties", {})
    plot_record = plot_node.get("record", {})
    plot_id = plot_record.get('id')
    plot_type = plot_properties.get("plotType", "Cross Section vs WIMP Mass")
    plot_name = plot_properties.get("name", f"Plot {plot_id}")

    # Delegate to the appropriate plot function based on plot type
    if plot_type == "Cross Section vs WIMP Mass":
        return plot_cross_section_vs_mass(plot_data, plot_id, plot_name, format_in=format_in)
    elif plot_type == "Cross Section / Mass [in GeV] vs Mass[GeV]":
        return plot_cross_section_div_mass(plot_data, plot_id, plot_name, format_in=format_in)
    elif plot_type == "Exclusion Curve":
        return plot_exclusion_curve(plot_data, plot_id, plot_name, format_in=format_in)
    else:
        # Default plot or unknown type
        return plot_default(plot_data, plot_id, plot_name)

def plot_cross_section_vs_mass(plot_data, plot_id, plot_name, format_in='svg'):
    """Create Cross Section vs WIMP Mass plot"""
    print('plotting - Cross Section vs WIMP Mass plot')
    fig, ax = create_standard_figure()

    # Extract properties
    plot_node = plot_data.get("plot_node", {})
    plot_properties = plot_node.get("properties", {})

    # Plot each dataset
    for display in plot_data.get("display_data", [{}]):
        display_properties = display.get('properties', {})
        style = display_properties.get('style', 'line')
        color = display_properties.get('color', 'black')
        print("style and color", style, color)

        # for data in display.get("data", []):
        for data_index, data in enumerate(display.get("data", [])):
            print("DATA:     ", data)
            data_properties = data.get('properties', {})
            y_rescale = float(data_properties.get('yRescale', 1))

            x_rescale = float(data_properties.get('xRescale', 1))
            x_units = data_properties.get('xUnits', 1)

            list_data = data_properties.get('values', [[[0.0, 0.0], [0.0, 1.0]]])
            #print("list_data>>>>>" ,list_data)

            # Plot each trace
            y_sigma1_lower = None
            y_sigma2_lower = None
            y_sigma1_upper = None
            y_sigma2_upper = None
            x_fill = None
            for index, trace in enumerate(list_data):
                x = [float(item[0]) * x_rescale for item in trace]

                selected_unit = plot_properties.get('xUnits', 'GeV/c^2')

                unit_x = [convert_mass_units(val, x_units, selected_unit)for val in x]

                y = [float(item[1]) * y_rescale for item in trace]

                # For the 'normal' lines, plot then exit the loop to move onto
                # the next dataset

                if data_index == 1:
                  ax.plot(unit_x, y, **kwargs_list[8])
                  continue

                elif data_index == 2:
                  ax.plot(unit_x, y, **kwargs_list[9])
                  continue

                elif data_index == 3:
                  ax.plot(unit_x, y, **kwargs_list[10])
                  continue

                # Fill line handled by this if else block
                # Store fill boundaries
                if order_list[index] == "-2sig":
                    y_sigma2_lower = y
                    x_fill = unit_x

                elif order_list[index] == "-1sig":
                    y_sigma1_lower = y
                    x_fill = unit_x

                elif order_list[index] == "2sig":
                    y_sigma2_upper = y
                    x_fill = unit_x

                elif order_list[index] == "1sig":
                    y_sigma1_upper = y
                    x_fill = unit_x

                # Otherwise it's a normal line
                else:
                    ax.plot(
                        unit_x,
                        y,
                        **kwargs_list[index]
                    )
            if data_index == 0:
              ax.fill_between(x_fill, y_sigma2_lower, y_sigma2_upper, **kwargs_list[2])
              ax.fill_between(x_fill, y_sigma1_lower, y_sigma1_upper, **kwargs_list[3])

    # Configure axes
    ax.set_xscale('log')
    # ax.set_xscale('linear')
    ax.set_yscale('log')

    # # Major tick every 1 GeV
    # ax.xaxis.set_major_locator(MultipleLocator(1))

    # # Minor tick every 0.2 GeV
    # ax.xaxis.set_minor_locator(MultipleLocator(0.2))

    ax.xaxis.set_major_locator(LogLocator(base=10))
    ax.xaxis.set_minor_locator(
        LogLocator(base=10, subs=np.arange(2, 10) * 0.1)
    )
    ax.xaxis.set_major_formatter(LogFormatterMathtext())

    ax.yaxis.set_major_locator(LogLocator(base=10))
    ax.yaxis.set_minor_locator(
        LogLocator(base=10, subs=np.arange(2, 10) * 0.1)
    )
    ax.yaxis.set_major_formatter(LogFormatterMathtext())

    # Set ranges
    set_axis_ranges(ax, plot_properties)

    # Set labels
    ax.set_ylabel(r"$\mathrm{DM-nucleon}\ \sigma_{\mathrm{SI}} \ [\mathrm{cm}^{2}]$", fontsize=18, labelpad=5)
    selected_unit = plot_properties.get('xUnits', 'GeV/c^2') ## will people know when to modify this??
    #ax.set_xlabel(get_x_label(selected_unit), fontsize=18)
    ax.set_xlabel(r"$\mathrm{DM \ Mass}\  [\mathrm{GeV/c^2}]$", fontsize=18, labelpad=5)

    # Set title
    plot_title = f"{plot_name} ({plot_id})"
    #ax.set_title(plot_title, fontsize=18, pad=5)

    # Set font
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["DejaVu Serif"],
        "mathtext.fontset": "cm"
    })

    for spine in ax.spines.values():
      spine.set_linewidth(1.4)

    # Set log formatting
    set_log_formatting(ax)

    # Save and return
    encoded_img = save_figure_to_base64(fig, format_in=format_in)
    return plot_name, encoded_img

def plot_cross_section_div_mass(plot_data, plot_id, plot_name, format_in='svg'):
    """Create Cross Section / Mass vs Mass plot"""
    fig, ax = create_standard_figure()

    # Similar implementation to plot_cross_section_vs_mass but with
    # appropriate calculations for this plot type

    # Extract properties
    plot_node = plot_data.get("plot_node", {})
    plot_properties = plot_node.get("properties", {})

    # Plot each dataset
    for display in plot_data.get("display_data", [{}]):
        display_properties = display.get('properties', {})
        style = display_properties.get('style', 'line')
        color = display_properties.get('color', 'black')

        for data in display.get("data", []):
            data_properties = data.get('properties', {})
            y_rescale = float(data_properties.get('yRescale', 1))
            x_rescale = float(data_properties.get('xRescale', 1))
            x_units = data_properties.get('xUnits', 1)

            list_data = data_properties.get('values', [[[0.0, 0.0], [0.0, 1.0]]])

            # Get style configuration
            line_kwargs = get_style_mpl(color, style)
            line_kwargs.pop('style', None)
            line_kwargs.pop('fill', None)

            fill_kwargs = get_style_mpl(color, style)
            fill_kwargs.pop('style', None)
            fill_kwargs.pop('marker', None)
            fill_kwargs.pop('markersize', None)
            fill_kwargs.pop('linestyle', None)
            fill_kwargs.pop('linewidth', None)
            fill_kwargs.pop('fill', None)

            # Plot each trace - note the different calculation for y values
            for trace in list_data:
                x = [float(item[0]) * x_rescale for item in trace]
                unit_x = [convert_mass_units(val, x_units, 'GeV') for val in x]
                y = [(float(item[1]) * y_rescale) / xi for item, xi in zip(trace, unit_x)]

                ax.plot(unit_x, y, **line_kwargs)
                if style == 'fill':
                    #ax.fill_between(unit_x, y, **fill_kwargs)
                    ax.fill(unit_x, y, **fill_kwargs)

    # Configure axes and other settings like in the first function
    ax.set_xscale('linear')
    ax.set_yscale('log')

    # Set ranges
    set_axis_ranges(ax, plot_properties)

    # Set labels with appropriate titles for this plot type
    ax.set_ylabel(r"$\mathrm{Cross\ Section/Mass}\ [cm^{2}/GeV]$", fontsize=18)
    ax.set_xlabel(r"$\mathrm{WIMP\ Mass}\ [GeV]$", fontsize=18)

    # Set title
    plot_title = f"{plot_name} ({plot_id})"
    ax.set_title(plot_title, fontsize=18)

    # Set log formatting
    set_log_formatting(ax)

    # Save and return
    encoded_img = save_figure_to_base64(fig, format_in=format_in)
    return plot_name, encoded_img

def plot_exclusion_curve(plot_data, plot_id, plot_name, format_in='svg'):
    """Create exclusion curve plot"""
    # Implementation for exclusion curves
    # Similar to previous functions but with specialized logic for exclusion curves
    fig, ax = create_standard_figure()

    # Implementation would go here...

    # Save and return
    encoded_img = save_figure_to_base64(fig)
    return plot_name, encoded_img

def plot_default(plot_data, plot_id, plot_name):
    """Create a default plot when type is unknown"""
    fig, ax = create_standard_figure()

    plot_data = get_empty_plot_data()

    # Simple implementation for generic data
    for display in plot_data.get("display_data", [{}]):
        for data in display.get("data", []):
            data_properties = data.get('properties', {})
            list_data = data_properties.get('values', [[[0.0, 0.0], [0.0, 1.0]]])

            for trace in list_data:
                x = [float(item[0]) for item in trace]
                y = [float(item[1]) for item in trace]
                ax.plot(x, y)

    ax.set_title(f"{plot_name} ({plot_id})")

    # Save and return
    encoded_img = save_figure_to_base64(fig)
    return plot_name, encoded_img


def set_axis_ranges(ax, plot_properties):
    """Set the X and Y axis ranges based on plot properties"""
    # X range
    xmin = plot_properties.get('xMin', '0')
    xmin = int(xmin)
    if xmin < 1:
        xmin = 1
    xmin = float(xmin) if xmin else 0
    xmax = plot_properties.get('xMax', '3')
    xmax = float(xmax) if xmax else 10000
    ax.set_xlim([xmin, xmax])

    # Y range (in log scale)
    ymin_exp = plot_properties.get('yMin', '-42')
    ymin_exp = float(ymin_exp) if ymin_exp else -42
    ymax_exp = plot_properties.get('yMax', '-42')
    ymax_exp = float(ymax_exp) if ymax_exp else -42
    ax.set_ylim([10**ymin_exp, 10**ymax_exp])

def set_log_formatting(ax):
    """Apply log formatting to axes"""
    try:
        from matplotlib.ticker import LogFormatterMathtext
        ax.xaxis.set_major_formatter(LogFormatterMathtext())
        ax.yaxis.set_major_formatter(LogFormatterMathtext())
        for label in ax.get_xticklabels() + ax.get_yticklabels():
            label.set_fontname('DejaVu Sans')
        # for label in ax.get_yticklabels():
        #     label.set_fontname('DejaVu Sans')
    except:
        pass  # Skip if formatter isn't available

def display_plot(url_in, filetype="svg"):
    """
    Displays an SVG or PDF from a base64-encoded string in Jupyter or HTML.

    Args:
        dmtools_plot_url (str): The base64-encoded image.
        filetype (str): "svg" or "pdf"
    """
    if filetype == "svg":
        html = f'<img src="data:image/svg+xml;base64,{url_in}" style="max-width:600px;"/>'
    elif filetype == "pdf":
        # Use <embed> or <iframe> for PDF display
        html = (
            f'<embed src="data:application/pdf;base64,{url_in}" '
            'type="application/pdf" width="600" height="600"/>'
        )
    else:
        raise ValueError("filetype must be 'svg' or 'pdf'")
    display(HTML(html))

def make_plot(format_in='svg'):
    plot_name, plot_url = set_plot_data(format_in=format_in)
    display_plot(plot_url, filetype=format_in)

In [72]:
# Your base64 string
plot_name, plot_url = set_plot_data(format_in='svg')

from IPython.display import Image, display

try:
    base64.b64decode(plot_url)
    print("Base64 is valid")
except Exception as e:
    print("Base64 is invalid:", e)

plot_data>>>>>>>>> {'plot_node': {'record': {'id': -1, 'type': 'Plot', 'created': '2025-07-26T14:46:37.430Z', 'updated': '2025-07-26T14:46:37.430Z'}, 'properties': {'name': 'Plot Example', 'xMax': 10000, 'xMin': 8, 'yMax': -44, 'yMin': -49, 'xUnits': 'GeV/c^2', 'yUnits': 'cm^2', 'plotType': 'Cross Section vs WIMP Mass'}}, 'display_data': [{'data': [{'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 52, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': 'LZ', 'greatestHit': 0, 'label': 'LZ 1 Jul 2025 WS2024', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'LZ Spokesperson richard_gaitskell@brown.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[['9.0', '9.797484060822151e-47'], ['11.0', '2.6404553011944104e-47'], ['13.0', '1.2143606153767551e-47'], ['16.0', '5.856844288044662e-48'], ['17.0', '5.045161843317137e-48'], ['19.0', '3.919409267394542e-48'], ['21.0', '3.264671412324803e-48'], ['23.0', '2.910809973414534e-48'], ['26.0', '2.5810717410182406e-48'], ['29.0', '2.4277055125156674e-48'], ['32.0', '2.2931217929082963e-48'], ['36.0', '2.2122904331621182e-48'], ['40.0', '2.1816833824484827e-48'], ['43.0', '2.217871458662707e-48'], ['46.0', '2.2681993499922688e-48'], ['65.0', '2.546041480288214e-48'], ['91.0', '3.214860921122965e-48'], ['129.0', '4.208919881771564e-48'], ['182.0', '5.533572054224652e-48'], ['256.0', '8.153750896244134e-48'], ['361.0', '1.0969733548583377e-47'], ['508.0', '1.546307933183269e-47'], ['1008.0', '3.056000501431157e-47'], ['2000.0', '5.732895978980354e-47'], ['5000.0', '1.4448421055253768e-46'], ['10000.0', '2.93003225261514e-46']], [['9.0', '6.360172460365096e-47'], ['11.0', '1.8701390104493043e-47'], ['13.0', '7.865482270647447e-48'], ['16.0', '4.048247623143398e-48'], ['17.0', '3.380911324758511e-48'], ['19.0', '2.4860846835481487e-48'], ['21.0', '1.97405947980569e-48'], ['23.0', '1.6875655008991387e-48'], ['26.0', '1.40693648954944e-48'], ['29.0', '1.2768077708783247e-48'], ['32.0', '1.2578359159028432e-48'], ['36.0', '1.2048026298661685e-48'], ['40.0', '1.2241600842374894e-48'], ['43.0', '1.2677965776635033e-48'], ['46.0', '1.319606104386345e-48'], ['65.0', '1.8083215589752695e-48'], ['91.0', '2.4014647187226817e-48'], ['129.0', '3.493040099638599e-48'], ['182.0', '4.819135224075079e-48'], ['256.0', '7.251921401221729e-48'], ['361.0', '9.787025883789508e-48'], ['508.0', '1.4317111324481653e-47'], ['1008.0', '2.786092050287613e-47'], ['2000.0', '5.38102575807705e-47'], ['5000.0', '1.3370021192602822e-46'], ['10000.0', '2.7701300636845517e-46']], [['9.0', '6.048606167873016e-47'], ['11.0', '1.4668916521102063e-47'], ['13.0', '6.349722880519739e-48'], ['16.0', '2.939552273941582e-48'], ['17.0', '2.372342435271395e-48'], ['19.0', '1.9579085670265272e-48'], ['21.0', '1.6446642309537584e-48'], ['23.0', '1.388198086098923e-48'], ['26.0', '1.2895890381231673e-48'], ['29.0', '1.1353477567166161e-48'], ['32.0', '1.0791741586353313e-48'], ['36.0', '1.0413430743896979e-48'], ['40.0', '1.0343922912479032e-48'], ['43.0', '1.0897886446843622e-48'], ['46.0', '1.0570195945594763e-48'], ['65.0', '1.2160842875189916e-48'], ['91.0', '1.4867353834743516e-48'], ['129.0', '1.9107273186768406e-48'], ['182.0', '2.549350955580449e-48'], ['256.0', '3.4986914786089955e-48'], ['361.0', '5.157222312027698e-48'], ['508.0', '7.094219706875709e-48'], ['1008.0', '1.3810780025559867e-47'], ['2000.0', '2.7321027795671195e-47'], ['5000.0', '6.697000339773429e-47'], ['10000.0', '1.3362203439327053e-46']], [['9.0', '9.893442198122728e-47'], ['11.0', '2.6918785823219344e-47'], ['13.0', '1.2302559129454687e-47'], ['16.0', '5.946384796102546e-48'], ['17.0', '5.16035714366596e-48'], ['19.0', '3.965616220973367e-48'], ['21.0', '3.323728873181861e-48'], ['23.0', '2.996213570149687e-48'], ['26.0', '2.624831549595038e-48'], ['29.0', '2.4562102316699348e-48'], ['32.0', '2.3339009812270167e-48'], ['36.0', '2.2666795304596937e-48'], ['40.0', '2.2464867009769235e-48'], ['43.0', '2.2483991280651468e-48'], ['46.0', '2.3032285368214262e-48'], ['65.0', '2.5816453787544615e-48'], ['91.0', '3.309866160233171e-48'], ['129.0', '4.313435146992405e-48'], ['182.0', '5.654047138734876e-48'], ['256.0', '8.249019845152288e-48'], ['361.0', '1.128688959698872e-47'], ['508.0', '1.575147654507888e-47'], ['1008.0', '3.135231270709062e-47'], ['2000.0', '5.937434002106777e-47'], ['5000.0', '1.4782897375478288e-46'], ['10000.0', '3.0008405080539785e-46']], [['9.0', '2.3145818978695027e-46'], ['11.0', '6.086757004761322e-47'], ['13.0', '2.828495679333201e-47'], ['16.0', '1.40000267517354e-47'], ['17.0', '1.1916648052774437e-47'], ['19.0', '9.302541001003626e-48'], ['21.0', '7.629776555527764e-48'], ['23.0', '6.860081746103876e-48'], ['26.0', '6.096427774422581e-48'], ['29.0', '5.601755116021929e-48'], ['32.0', '5.309316082917047e-48'], ['36.0', '5.090681232958277e-48'], ['40.0', '5.0587223537493065e-48'], ['43.0', '5.055364644860216e-48'], ['46.0', '5.1954036449868804e-48'], ['65.0', '5.992802958751586e-48'], ['91.0', '7.422458464315766e-48'], ['129.0', '9.767779832306256e-48'], ['182.0', '1.3198015721888574e-47'], ['256.0', '1.8325636140177053e-47'], ['361.0', '2.5026197499670055e-47'], ['508.0', '3.458283462086202e-47'], ['1008.0', '6.833958871618215e-47'], ['2000.0', '1.3394627139951759e-46'], ['5000.0', '3.3556730400544437e-46'], ['10000.0', '6.683686263656167e-46']], [['9.0', '4.194714251898931e-46'], ['11.0', '1.1040826054423953e-46'], ['13.0', '4.924628262308908e-47'], ['16.0', '2.4672118233111775e-47'], ['17.0', '2.1087352871554742e-47'], ['19.0', '1.6509184360336717e-47'], ['21.0', '1.3745886244053102e-47'], ['23.0', '1.208340705478538e-47'], ['26.0', '1.064602898282829e-47'], ['29.0', '9.912336962513661e-48'], ['32.0', '9.460588314015946e-48'], ['36.0', '9.27440911921791e-48'], ['40.0', '8.987337280871959e-48'], ['43.0', '9.188354660507748e-48'], ['46.0', '9.28590178459593e-48'], ['65.0', '1.0681313676739283e-47'], ['91.0', '1.3172503783042412e-47'], ['129.0', '1.7440438780969673e-47'], ['182.0', '2.372815458103765e-47'], ['256.0', '3.221795344715976e-47'], ['361.0', '4.464177661067317e-47'], ['508.0', '6.271633584988651e-47'], ['1008.0', '1.2107487584832586e-46'], ['2000.0', '2.4144311800237557e-46'], ['5000.0', '6.086069411404099e-46'], ['10000.0', '1.2159498899422127e-45']], [['9.0', '6.208987087138066e-46'], ['11.0', '1.6262330084733883e-46'], ['13.0', '7.376376970640113e-47'], ['16.0', '3.7146785808211216e-47'], ['17.0', '3.156239326479482e-47'], ['19.0', '2.469739802410441e-47'], ['21.0', '2.0579363976500567e-47'], ['23.0', '1.8485837979688936e-47'], ['26.0', '1.6309150887888171e-47'], ['29.0', '1.4985345570517207e-47'], ['32.0', '1.4255652332998049e-47'], ['36.0', '1.3746957151160644e-47'], ['40.0', '1.3853719064038475e-47'], ['43.0', '1.3950160690853623e-47'], ['46.0', '1.4029246977096138e-47'], ['65.0', '1.6256543545704663e-47'], ['91.0', '2.0170849900045724e-47'], ['129.0', '2.6443911225181474e-47'], ['182.0', '3.593638519780333e-47'], ['256.0', '4.910927822407369e-47'], ['361.0', '6.871267727900406e-47'], ['508.0', '9.606846430394522e-47'], ['1008.0', '1.874095488915199e-46'], ['2000.0', '3.704861397809596e-46'], ['5000.0', '9.227400695280647e-46'], ['10000.0', '1.8488843634379313e-45']], [['9.0', '4.40806591887947e-46'], ['11.0', '1.223210047579738e-46'], ['13.0', '5.60645601807054e-47'], ['16.0', '2.8047930866531153e-47'], ['17.0', '2.403883883122198e-47'], ['19.0', '1.8837459711105122e-47'], ['21.0', '1.5897316772219757e-47'], ['23.0', '1.4069556914646076e-47'], ['26.0', '1.2305328218712188e-47'], ['29.0', '1.148610127865671e-47'], ['32.0', '1.0956105766300616e-47'], ['36.0', '1.0714219400455744e-47'], ['40.0', '1.0617376217763808e-47'], ['43.0', '1.0642928750477521e-47'], ['46.0', '1.0788381790948551e-47'], ['65.0', '1.2387941905136282e-47'], ['91.0', '1.5441766760162665e-47'], ['129.0', '2.0515058467201082e-47'], ['182.0', '2.7689176158123063e-47'], ['256.0', '3.8191599823138155e-47'], ['361.0', '5.272945272912351e-47'], ['508.0', '7.368551894569787e-47'], ['1008.0', '1.44399629947039e-46'], ['2000.0', '2.8596906406277796e-46'], ['5000.0', '7.082048951811102e-46'], ['10000.0', '1.4217307671255365e-45']]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[6.0, 3.081e-44], [7.0, 7.318e-45], [8.0, 2.4769999999999997e-45], [9.0, 1.072e-45], [10.0, 5.5270000000000005e-46], [11.0, 3.248e-46], [12.0, 2.1080000000000002e-46], [13.0, 1.477e-46], [15.0, 8.594999999999999e-47], [17.0, 5.865999999999999e-47], [20.0, 4.0049999999999996e-47], [23.0, 3.16e-47], [25.0, 2.838e-47], [26.0, 2.719e-47], [28.14, 2.587e-47], [30.0, 2.6159999999999996e-47], [35.0, 2.761e-47], [40.0, 2.9600000000000003e-47], [45.0, 3.188e-47], [50.0, 3.431e-47], [55.0, 3.683e-47], [60.0, 3.939e-47], [70.0, 4.458e-47], [75.0, 4.722e-47], [80.0, 4.987999999999999e-47], [90.0, 5.527e-47], [100.0, 6.074e-47], [125.0, 7.468e-47], [150.0, 8.887e-47], [200.0, 1.1760000000000002e-46], [500.0, 2.8570000000000003e-46], [1000.0, 5.6360000000000005e-46], [10000.0, 5.635999999999999e-45]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[9.0, 3.88141e-46], [11.0, 1.05545e-46], [13.0, 4.40606e-47], [16.0, 2.28511e-47], [17.0, 1.88394e-47], [19.0, 1.55761e-47], [21.0, 1.31963e-47], [23.0, 1.15272e-47], [26.0, 1.0176e-47], [29.0, 9.53429e-48], [30.0, 9.37582e-48], [32.0, 9.27823e-48], [36.0, 9.16769e-48], [40.0, 9.49545e-48], [43.0, 1.02165e-47], [46.0, 1.13143e-47], [55.0, 1.43786e-47], [65.0, 1.76318e-47], [78.0, 2.19292e-47], [91.0, 2.53863e-47], [110.0, 3.0379e-47], [129.0, 3.64334e-47], [155.0, 4.47954e-47], [182.0, 5.15116e-47], [219.0, 6.34341e-47], [256.0, 7.3676e-47], [308.0, 8.85464e-47], [361.0, 1.01762e-46], [434.0, 1.24217e-46], [508.0, 1.46316e-46], [612.0, 1.77592e-46], [716.0, 2.00948e-46], [862.0, 2.42561e-46], [1008.0, 2.89452e-46], [1214.0, 3.48215e-46], [1420.0, 4.09394e-46], [1710.0, 4.86699e-46], [2000.0, 5.75993e-46], [5000.0, 1.45172e-45], [10000.0, 2.79882e-45]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[5.0, 2.57864e-42], [5.52604925753, 3.73831792376e-43], [6.10744407932, 8.635083692880001e-44], [6.75000736398, 2.84216851286e-44], [7.46017463641, 1.19523122621e-44], [8.24505850211, 5.95781477285e-45], [9.11251988276, 3.34432334181e-45], [10.0712467465, 2.0094789900999998e-45], [11.1308411211, 1.25299981456e-45], [12.3019152626, 8.37642328364e-46], [13.5961979406, 6.0585486397099995e-46], [15.026651907, 4.48509058883e-46], [16.6076037228, 3.39621746367e-46], [18.3548872443, 2.71387884921e-46], [20.2860022057, 2.27325122753e-46], [22.4202894853, 1.9480152764e-46], [24.7791248128, 1.6911710338099999e-46], [27.3861328548, 1.48750826074e-46], [30.2674238257, 1.32590361258e-46], [33.4518549919, 1.19797916751e-46], [36.9713196882, 1.09742627368e-46], [40.8610667425, 1.0426205417200001e-46], [45.1600535068, 1.0760481873699998e-46], [49.9113360303, 1.12030153826e-46], [55.1625002824, 1.17345516876e-46], [60.9661387458, 1.23563229653e-46], [67.3803771501, 1.3076316635400001e-46], [74.4694566244, 1.39039207431e-46], [82.3043770976, 1.4850020980199999e-46], [90.9636083902, 1.59271118389e-46], [100.533876121, 1.71494193821e-46], [111.111030299, 1.85330326738e-46], [122.801005298, 2.00960402158e-46], [135.72088083, 2.18586668224e-46], [150.000054548, 2.38434052086e-46], [165.781538013, 2.6075135174399998e-46], [183.223389009, 2.8581221632800003e-46], [202.500294559, 3.13915808751e-46], [223.80532048, 3.45387024072e-46], [247.351845013, 3.80576114978e-46], [273.375695897, 4.19857553116e-46], [302.137512267, 4.63627932896e-46], [333.925355067, 5.12302704286e-46], [369.057592088, 5.663115050789999e-46], [407.886086548, 6.26092070482e-46], [450.799721145, 6.9213601545299994e-46], [498.228292865, 7.65082433367e-46], [550.646817573, 8.45653030517e-46], [608.580287482, 9.34645771884e-46], [672.608929157, 1.03294309969e-45], [743.374014714, 1.14152106187e-45], [821.584284415, 1.26145945447e-45], [908.023044978, 1.39395309425e-45], [1003.5560147, 1.54032435153e-45], [1109.13999399, 1.7020375011199998e-45], [1225.83244805, 1.88071562886e-45], [1354.80209788, 2.0781573926800002e-45], [1497.34062542, 2.29635623762e-45], [1654.87561027, 2.5375221269399998e-45], [1828.98482749, 2.80410578489e-45], [2021.4120496, 3.09882575248e-45], [2234.08451116, 3.4246985956799996e-45], [2469.13221083, 3.7850726477699995e-45], [2728.90924408, 4.18366571556e-45], [3016.01738042, 4.62460723406e-45], [3333.33212116, 5.11248541504e-45], [3684.03149864, 5.6524000054e-45], [4071.62790555, 6.25002109637e-45], [4500.00327288, 6.91157474944e-45], [4973.44794899, 7.643751436539999e-45], [5496.70366918, 8.45386796442e-45], [6075.01104598, 9.349945089209999e-45], [6714.16205602, 1.03407655694e-44], [7420.55804891, 1.14359354288e-44], [8201.27385933, 1.2645948344700002e-44], [9064.12866422, 1.39822530209e-44], [10017.764295, 1.54573233392e-44], [11071.7317889, 1.7084731008599999e-44], [12236.5870463, 1.88792203464e-44], [13523.9965524, 2.08567847283e-44], [14946.8542214, 2.30347441396e-44], [16519.4105345, 2.5431823137399996e-44], [18257.4152638, 2.80682284059e-44], [20178.2752126, 3.09657255138e-44], [22301.2285513, 3.4148874098e-44], [24647.5374956, 3.76483454204e-44], [27240.7012555, 4.1499604980999995e-44], [30106.6913895, 4.57430145847e-44], [33274.2119199, 5.04246091756e-44], [36774.9868149, 5.55970087402e-44], [40644.0777168, 6.13204913206e-44], [44920.235098, 6.76642586901e-44], [49646.2863622, 7.47079330103e-44], [54869.5647782, 8.25433311155e-44], [60642.3835407, 9.127657335899999e-44], [67022.5597079, 1.01030596683e-43], [74073.9932623, 1.11948157375e-43], [81867.3070938, 1.24195428646e-43], [90480.5543163, 1.37966322722e-43], [100000.0, 1.53487697882e-43]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}], 'record': {'id': -1, 'type': 'Display', 'created': '2025-07-26T14:46:37.430Z', 'updated': '2025-07-26T14:46:37.430Z'}, 'properties': {'color': 'black', 'style': 'line'}}]}
plotting - Cross Section vs WIMP Mass plot
style and color line black

In [73]:
make_plot(format_in='svg')

plot_data>>>>>>>>> {'plot_node': {'record': {'id': -1, 'type': 'Plot', 'created': '2025-07-26T14:46:37.430Z', 'updated': '2025-07-26T14:46:37.430Z'}, 'properties': {'name': 'Plot Example', 'xMax': 10000, 'xMin': 8, 'yMax': -44, 'yMin': -49, 'xUnits': 'GeV/c^2', 'yUnits': 'cm^2', 'plotType': 'Cross Section vs WIMP Mass'}}, 'display_data': [{'data': [{'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 52, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': 'LZ', 'greatestHit': 0, 'label': 'LZ 1 Jul 2025 WS2024', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'LZ Spokesperson richard_gaitskell@brown.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[['9.0', '9.797484060822151e-47'], ['11.0', '2.6404553011944104e-47'], ['13.0', '1.2143606153767551e-47'], ['16.0', '5.856844288044662e-48'], ['17.0', '5.045161843317137e-48'], ['19.0', '3.919409267394542e-48'], ['21.0', '3.264671412324803e-48'], ['23.0', '2.910809973414534e-48'], ['26.0', '2.5810717410182406e-48'], ['29.0', '2.4277055125156674e-48'], ['32.0', '2.2931217929082963e-48'], ['36.0', '2.2122904331621182e-48'], ['40.0', '2.1816833824484827e-48'], ['43.0', '2.217871458662707e-48'], ['46.0', '2.2681993499922688e-48'], ['65.0', '2.546041480288214e-48'], ['91.0', '3.214860921122965e-48'], ['129.0', '4.208919881771564e-48'], ['182.0', '5.533572054224652e-48'], ['256.0', '8.153750896244134e-48'], ['361.0', '1.0969733548583377e-47'], ['508.0', '1.546307933183269e-47'], ['1008.0', '3.056000501431157e-47'], ['2000.0', '5.732895978980354e-47'], ['5000.0', '1.4448421055253768e-46'], ['10000.0', '2.93003225261514e-46']], [['9.0', '6.360172460365096e-47'], ['11.0', '1.8701390104493043e-47'], ['13.0', '7.865482270647447e-48'], ['16.0', '4.048247623143398e-48'], ['17.0', '3.380911324758511e-48'], ['19.0', '2.4860846835481487e-48'], ['21.0', '1.97405947980569e-48'], ['23.0', '1.6875655008991387e-48'], ['26.0', '1.40693648954944e-48'], ['29.0', '1.2768077708783247e-48'], ['32.0', '1.2578359159028432e-48'], ['36.0', '1.2048026298661685e-48'], ['40.0', '1.2241600842374894e-48'], ['43.0', '1.2677965776635033e-48'], ['46.0', '1.319606104386345e-48'], ['65.0', '1.8083215589752695e-48'], ['91.0', '2.4014647187226817e-48'], ['129.0', '3.493040099638599e-48'], ['182.0', '4.819135224075079e-48'], ['256.0', '7.251921401221729e-48'], ['361.0', '9.787025883789508e-48'], ['508.0', '1.4317111324481653e-47'], ['1008.0', '2.786092050287613e-47'], ['2000.0', '5.38102575807705e-47'], ['5000.0', '1.3370021192602822e-46'], ['10000.0', '2.7701300636845517e-46']], [['9.0', '6.048606167873016e-47'], ['11.0', '1.4668916521102063e-47'], ['13.0', '6.349722880519739e-48'], ['16.0', '2.939552273941582e-48'], ['17.0', '2.372342435271395e-48'], ['19.0', '1.9579085670265272e-48'], ['21.0', '1.6446642309537584e-48'], ['23.0', '1.388198086098923e-48'], ['26.0', '1.2895890381231673e-48'], ['29.0', '1.1353477567166161e-48'], ['32.0', '1.0791741586353313e-48'], ['36.0', '1.0413430743896979e-48'], ['40.0', '1.0343922912479032e-48'], ['43.0', '1.0897886446843622e-48'], ['46.0', '1.0570195945594763e-48'], ['65.0', '1.2160842875189916e-48'], ['91.0', '1.4867353834743516e-48'], ['129.0', '1.9107273186768406e-48'], ['182.0', '2.549350955580449e-48'], ['256.0', '3.4986914786089955e-48'], ['361.0', '5.157222312027698e-48'], ['508.0', '7.094219706875709e-48'], ['1008.0', '1.3810780025559867e-47'], ['2000.0', '2.7321027795671195e-47'], ['5000.0', '6.697000339773429e-47'], ['10000.0', '1.3362203439327053e-46']], [['9.0', '9.893442198122728e-47'], ['11.0', '2.6918785823219344e-47'], ['13.0', '1.2302559129454687e-47'], ['16.0', '5.946384796102546e-48'], ['17.0', '5.16035714366596e-48'], ['19.0', '3.965616220973367e-48'], ['21.0', '3.323728873181861e-48'], ['23.0', '2.996213570149687e-48'], ['26.0', '2.624831549595038e-48'], ['29.0', '2.4562102316699348e-48'], ['32.0', '2.3339009812270167e-48'], ['36.0', '2.2666795304596937e-48'], ['40.0', '2.2464867009769235e-48'], ['43.0', '2.2483991280651468e-48'], ['46.0', '2.3032285368214262e-48'], ['65.0', '2.5816453787544615e-48'], ['91.0', '3.309866160233171e-48'], ['129.0', '4.313435146992405e-48'], ['182.0', '5.654047138734876e-48'], ['256.0', '8.249019845152288e-48'], ['361.0', '1.128688959698872e-47'], ['508.0', '1.575147654507888e-47'], ['1008.0', '3.135231270709062e-47'], ['2000.0', '5.937434002106777e-47'], ['5000.0', '1.4782897375478288e-46'], ['10000.0', '3.0008405080539785e-46']], [['9.0', '2.3145818978695027e-46'], ['11.0', '6.086757004761322e-47'], ['13.0', '2.828495679333201e-47'], ['16.0', '1.40000267517354e-47'], ['17.0', '1.1916648052774437e-47'], ['19.0', '9.302541001003626e-48'], ['21.0', '7.629776555527764e-48'], ['23.0', '6.860081746103876e-48'], ['26.0', '6.096427774422581e-48'], ['29.0', '5.601755116021929e-48'], ['32.0', '5.309316082917047e-48'], ['36.0', '5.090681232958277e-48'], ['40.0', '5.0587223537493065e-48'], ['43.0', '5.055364644860216e-48'], ['46.0', '5.1954036449868804e-48'], ['65.0', '5.992802958751586e-48'], ['91.0', '7.422458464315766e-48'], ['129.0', '9.767779832306256e-48'], ['182.0', '1.3198015721888574e-47'], ['256.0', '1.8325636140177053e-47'], ['361.0', '2.5026197499670055e-47'], ['508.0', '3.458283462086202e-47'], ['1008.0', '6.833958871618215e-47'], ['2000.0', '1.3394627139951759e-46'], ['5000.0', '3.3556730400544437e-46'], ['10000.0', '6.683686263656167e-46']], [['9.0', '4.194714251898931e-46'], ['11.0', '1.1040826054423953e-46'], ['13.0', '4.924628262308908e-47'], ['16.0', '2.4672118233111775e-47'], ['17.0', '2.1087352871554742e-47'], ['19.0', '1.6509184360336717e-47'], ['21.0', '1.3745886244053102e-47'], ['23.0', '1.208340705478538e-47'], ['26.0', '1.064602898282829e-47'], ['29.0', '9.912336962513661e-48'], ['32.0', '9.460588314015946e-48'], ['36.0', '9.27440911921791e-48'], ['40.0', '8.987337280871959e-48'], ['43.0', '9.188354660507748e-48'], ['46.0', '9.28590178459593e-48'], ['65.0', '1.0681313676739283e-47'], ['91.0', '1.3172503783042412e-47'], ['129.0', '1.7440438780969673e-47'], ['182.0', '2.372815458103765e-47'], ['256.0', '3.221795344715976e-47'], ['361.0', '4.464177661067317e-47'], ['508.0', '6.271633584988651e-47'], ['1008.0', '1.2107487584832586e-46'], ['2000.0', '2.4144311800237557e-46'], ['5000.0', '6.086069411404099e-46'], ['10000.0', '1.2159498899422127e-45']], [['9.0', '6.208987087138066e-46'], ['11.0', '1.6262330084733883e-46'], ['13.0', '7.376376970640113e-47'], ['16.0', '3.7146785808211216e-47'], ['17.0', '3.156239326479482e-47'], ['19.0', '2.469739802410441e-47'], ['21.0', '2.0579363976500567e-47'], ['23.0', '1.8485837979688936e-47'], ['26.0', '1.6309150887888171e-47'], ['29.0', '1.4985345570517207e-47'], ['32.0', '1.4255652332998049e-47'], ['36.0', '1.3746957151160644e-47'], ['40.0', '1.3853719064038475e-47'], ['43.0', '1.3950160690853623e-47'], ['46.0', '1.4029246977096138e-47'], ['65.0', '1.6256543545704663e-47'], ['91.0', '2.0170849900045724e-47'], ['129.0', '2.6443911225181474e-47'], ['182.0', '3.593638519780333e-47'], ['256.0', '4.910927822407369e-47'], ['361.0', '6.871267727900406e-47'], ['508.0', '9.606846430394522e-47'], ['1008.0', '1.874095488915199e-46'], ['2000.0', '3.704861397809596e-46'], ['5000.0', '9.227400695280647e-46'], ['10000.0', '1.8488843634379313e-45']], [['9.0', '4.40806591887947e-46'], ['11.0', '1.223210047579738e-46'], ['13.0', '5.60645601807054e-47'], ['16.0', '2.8047930866531153e-47'], ['17.0', '2.403883883122198e-47'], ['19.0', '1.8837459711105122e-47'], ['21.0', '1.5897316772219757e-47'], ['23.0', '1.4069556914646076e-47'], ['26.0', '1.2305328218712188e-47'], ['29.0', '1.148610127865671e-47'], ['32.0', '1.0956105766300616e-47'], ['36.0', '1.0714219400455744e-47'], ['40.0', '1.0617376217763808e-47'], ['43.0', '1.0642928750477521e-47'], ['46.0', '1.0788381790948551e-47'], ['65.0', '1.2387941905136282e-47'], ['91.0', '1.5441766760162665e-47'], ['129.0', '2.0515058467201082e-47'], ['182.0', '2.7689176158123063e-47'], ['256.0', '3.8191599823138155e-47'], ['361.0', '5.272945272912351e-47'], ['508.0', '7.368551894569787e-47'], ['1008.0', '1.44399629947039e-46'], ['2000.0', '2.8596906406277796e-46'], ['5000.0', '7.082048951811102e-46'], ['10000.0', '1.4217307671255365e-45']]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[6.0, 3.081e-44], [7.0, 7.318e-45], [8.0, 2.4769999999999997e-45], [9.0, 1.072e-45], [10.0, 5.5270000000000005e-46], [11.0, 3.248e-46], [12.0, 2.1080000000000002e-46], [13.0, 1.477e-46], [15.0, 8.594999999999999e-47], [17.0, 5.865999999999999e-47], [20.0, 4.0049999999999996e-47], [23.0, 3.16e-47], [25.0, 2.838e-47], [26.0, 2.719e-47], [28.14, 2.587e-47], [30.0, 2.6159999999999996e-47], [35.0, 2.761e-47], [40.0, 2.9600000000000003e-47], [45.0, 3.188e-47], [50.0, 3.431e-47], [55.0, 3.683e-47], [60.0, 3.939e-47], [70.0, 4.458e-47], [75.0, 4.722e-47], [80.0, 4.987999999999999e-47], [90.0, 5.527e-47], [100.0, 6.074e-47], [125.0, 7.468e-47], [150.0, 8.887e-47], [200.0, 1.1760000000000002e-46], [500.0, 2.8570000000000003e-46], [1000.0, 5.6360000000000005e-46], [10000.0, 5.635999999999999e-45]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[9.0, 3.88141e-46], [11.0, 1.05545e-46], [13.0, 4.40606e-47], [16.0, 2.28511e-47], [17.0, 1.88394e-47], [19.0, 1.55761e-47], [21.0, 1.31963e-47], [23.0, 1.15272e-47], [26.0, 1.0176e-47], [29.0, 9.53429e-48], [30.0, 9.37582e-48], [32.0, 9.27823e-48], [36.0, 9.16769e-48], [40.0, 9.49545e-48], [43.0, 1.02165e-47], [46.0, 1.13143e-47], [55.0, 1.43786e-47], [65.0, 1.76318e-47], [78.0, 2.19292e-47], [91.0, 2.53863e-47], [110.0, 3.0379e-47], [129.0, 3.64334e-47], [155.0, 4.47954e-47], [182.0, 5.15116e-47], [219.0, 6.34341e-47], [256.0, 7.3676e-47], [308.0, 8.85464e-47], [361.0, 1.01762e-46], [434.0, 1.24217e-46], [508.0, 1.46316e-46], [612.0, 1.77592e-46], [716.0, 2.00948e-46], [862.0, 2.42561e-46], [1008.0, 2.89452e-46], [1214.0, 3.48215e-46], [1420.0, 4.09394e-46], [1710.0, 4.86699e-46], [2000.0, 5.75993e-46], [5000.0, 1.45172e-45], [10000.0, 2.79882e-45]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}, {'record': {'archived': None, 'created': 'Tue, 21 Jan 2025 14:22:36 GMT', 'id': 58, 'type': 'Data', 'updated': 'Tue, 21 Jan 2025 14:22:36 GMT'}, 'properties': {'comment': 'sigma normalized to DM-Nucleon', 'dateAnnouncement': '2025-07-01', 'dateEnd': None, 'dateOfficial': None, 'dateStart': None, 'defaultColor': 'blue', 'defaultStyle': 'line', 'experiment': '', 'greatestHit': 0, 'label': 'XenonNT', 'label_short': 'LZ 1 Jul 2025', 'measurementType': 'Dir', 'official': 1, 'open': 0, 'public': 0, 'rating': 80, 'raw': '{}', 'reference': 'XenonNT Spokesperson blah@school.edu', 'resultType': 'Other', 'spinDependency': 'SI', 'values': [[[5.0, 2.57864e-42], [5.52604925753, 3.73831792376e-43], [6.10744407932, 8.635083692880001e-44], [6.75000736398, 2.84216851286e-44], [7.46017463641, 1.19523122621e-44], [8.24505850211, 5.95781477285e-45], [9.11251988276, 3.34432334181e-45], [10.0712467465, 2.0094789900999998e-45], [11.1308411211, 1.25299981456e-45], [12.3019152626, 8.37642328364e-46], [13.5961979406, 6.0585486397099995e-46], [15.026651907, 4.48509058883e-46], [16.6076037228, 3.39621746367e-46], [18.3548872443, 2.71387884921e-46], [20.2860022057, 2.27325122753e-46], [22.4202894853, 1.9480152764e-46], [24.7791248128, 1.6911710338099999e-46], [27.3861328548, 1.48750826074e-46], [30.2674238257, 1.32590361258e-46], [33.4518549919, 1.19797916751e-46], [36.9713196882, 1.09742627368e-46], [40.8610667425, 1.0426205417200001e-46], [45.1600535068, 1.0760481873699998e-46], [49.9113360303, 1.12030153826e-46], [55.1625002824, 1.17345516876e-46], [60.9661387458, 1.23563229653e-46], [67.3803771501, 1.3076316635400001e-46], [74.4694566244, 1.39039207431e-46], [82.3043770976, 1.4850020980199999e-46], [90.9636083902, 1.59271118389e-46], [100.533876121, 1.71494193821e-46], [111.111030299, 1.85330326738e-46], [122.801005298, 2.00960402158e-46], [135.72088083, 2.18586668224e-46], [150.000054548, 2.38434052086e-46], [165.781538013, 2.6075135174399998e-46], [183.223389009, 2.8581221632800003e-46], [202.500294559, 3.13915808751e-46], [223.80532048, 3.45387024072e-46], [247.351845013, 3.80576114978e-46], [273.375695897, 4.19857553116e-46], [302.137512267, 4.63627932896e-46], [333.925355067, 5.12302704286e-46], [369.057592088, 5.663115050789999e-46], [407.886086548, 6.26092070482e-46], [450.799721145, 6.9213601545299994e-46], [498.228292865, 7.65082433367e-46], [550.646817573, 8.45653030517e-46], [608.580287482, 9.34645771884e-46], [672.608929157, 1.03294309969e-45], [743.374014714, 1.14152106187e-45], [821.584284415, 1.26145945447e-45], [908.023044978, 1.39395309425e-45], [1003.5560147, 1.54032435153e-45], [1109.13999399, 1.7020375011199998e-45], [1225.83244805, 1.88071562886e-45], [1354.80209788, 2.0781573926800002e-45], [1497.34062542, 2.29635623762e-45], [1654.87561027, 2.5375221269399998e-45], [1828.98482749, 2.80410578489e-45], [2021.4120496, 3.09882575248e-45], [2234.08451116, 3.4246985956799996e-45], [2469.13221083, 3.7850726477699995e-45], [2728.90924408, 4.18366571556e-45], [3016.01738042, 4.62460723406e-45], [3333.33212116, 5.11248541504e-45], [3684.03149864, 5.6524000054e-45], [4071.62790555, 6.25002109637e-45], [4500.00327288, 6.91157474944e-45], [4973.44794899, 7.643751436539999e-45], [5496.70366918, 8.45386796442e-45], [6075.01104598, 9.349945089209999e-45], [6714.16205602, 1.03407655694e-44], [7420.55804891, 1.14359354288e-44], [8201.27385933, 1.2645948344700002e-44], [9064.12866422, 1.39822530209e-44], [10017.764295, 1.54573233392e-44], [11071.7317889, 1.7084731008599999e-44], [12236.5870463, 1.88792203464e-44], [13523.9965524, 2.08567847283e-44], [14946.8542214, 2.30347441396e-44], [16519.4105345, 2.5431823137399996e-44], [18257.4152638, 2.80682284059e-44], [20178.2752126, 3.09657255138e-44], [22301.2285513, 3.4148874098e-44], [24647.5374956, 3.76483454204e-44], [27240.7012555, 4.1499604980999995e-44], [30106.6913895, 4.57430145847e-44], [33274.2119199, 5.04246091756e-44], [36774.9868149, 5.55970087402e-44], [40644.0777168, 6.13204913206e-44], [44920.235098, 6.76642586901e-44], [49646.2863622, 7.47079330103e-44], [54869.5647782, 8.25433311155e-44], [60642.3835407, 9.127657335899999e-44], [67022.5597079, 1.01030596683e-43], [74073.9932623, 1.11948157375e-43], [81867.3070938, 1.24195428646e-43], [90480.5543163, 1.37966322722e-43], [100000.0, 1.53487697882e-43]]], 'xRescale': '1', 'xUnits': 'GeV', 'yRescale': '1', 'yUnits': 'cm^2', 'year': 2025}}], 'record': {'id': -1, 'type': 'Display', 'created': '2025-07-26T14:46:37.430Z', 'updated': '2025-07-26T14:46:37.430Z'}, 'properties': {'color': 'black', 'style': 'line'}}]}
plotting - Cross Section vs WIMP Mass plot
style and color line black

In [ ]:
def set_legend_data(format_in='svg'):
    ### get legend
    # Retrieve plot data
    # plot_id_int = int(plot_id)
    # plot_data, status_code = get_current_plots_data(), 1
    data = get_current_plots_data(LZ_2026)
    print("data-->")
    #print(json.dumps(data, indent=4))
    plot_data = data.get('dmtools_current_plot')
    print("plot_data-->")
    #print(json.dumps(plot_data, indent=4))
    # Extract plot type and other key properties
    plot_node = plot_data.get("plot_node", {})
    plot_properties = plot_node.get("properties", {})
    plot_record = plot_node.get("record", {})
    plot_id = plot_record.get('id')
    plot_type = plot_properties.get("plotType", "Cross Section vs WIMP Mass")
    plot_name = plot_properties.get("name", f"Plot {plot_id}")
    # print("plot_operations plot_record >>>>", plot_data.get('plot_record'))
    plot_data_cache = plot_data
    # print("plot_operations - plot_record_cache >>>>", plot_data_cache.get('plot_record'))

    handles = []
    for display in plot_data.get("display_data", [{}]):
        display_properties = display.get('properties', {})
        style = display_properties.get('style', 'line')
        color = display_properties.get('color', 'black')

        for data in display.get("data", []):
            data_record = data.get('record',{})
            print("data_record-->")
            print(json.dumps(data_record, indent=4))
            data_record_id = data_record.get('id',-1)
            data_properties = data.get('properties',{})
            ##print(f"    Data Node (Legend) - ID: {data_record.get('id')}, Type: {data_record.get('type')}, \
            ##       Created At: {data_record.get('created')}, Updated At: {data_record.get('updated')}")

            trace_name = "(" + str(data_record_id) + "):" + data_properties.get('label_short','')
            style = display_properties.get('style','line')
            color = display_properties.get('color','black')

            line_plot_kwargs = get_style_mpl(color,style)
            line_plot_kwargs.pop('style',None)
            line_plot_kwargs.pop('fill',None)

            fill_plot_kwargs = get_style_mpl(color,style)
            fill_plot_kwargs.pop('style',None)
            fill_plot_kwargs.pop('marker',None)
            fill_plot_kwargs.pop('markersize',None)

            if style != 'fill':
                append_this = mlines.Line2D([], [], label=trace_name, **line_plot_kwargs)
            else:
                append_this = mpatches.Patch(label=trace_name, **fill_plot_kwargs)

            handles.append(append_this)

    labels = [handle.get_label() for handle in handles]

    #px = 1/plt.rcParams['figure.dpi']  # pixel in inches
    px = 1/100  # pixel in inches

    num_points = len(labels)
    #fig_height = num_points * 10 * px
    #fig_width = 5

    fig, ax = plt.subplots(figsize=(10,10), edgecolor='#FFFFFF', facecolor='#FFFFFF')
    #ax.set_facecolor('white')

    legend = ax.legend(handles=handles, labels=labels, loc='upper center', fontsize=24, labelspacing=1, facecolor='white')
    # Make legend background solid white
    legend.get_frame().set_alpha(1)  # Set alpha to 1 for solid background
    legend.get_frame().set_facecolor((1, 1, 1))  # Set the background to white

    ax.axis('off')  # Hide the axes

    # Save as SVG
    img_svg = io.BytesIO()
    fig.savefig(img_svg, format='svg', dpi=100, bbox_inches='tight', pad_inches=0.2)
    img_svg.seek(0)
    dmtools_legend_url = base64.b64encode(img_svg.getvalue()).decode('utf8')

    # Save as PDF
    img_pdf = io.BytesIO()
    fig.savefig(img_pdf, format='pdf', dpi=100, bbox_inches='tight', pad_inches=0.2)
    img_pdf.seek(0)
    dmtools_legend_url_pdf = base64.b64encode(img_pdf.getvalue()).decode('utf8')

    # Now close the figure
    plt.close(fig)

    return dmtools_legend_url

In [ ]:
def display_legend(url_in, filetype="svg"):
    """
    Displays an SVG or PDF from a base64-encoded string in Jupyter or HTML.

    Args:
        dmtools_plot_url (str): The base64-encoded image.
        filetype (str): "svg" or "pdf"
    """
    if filetype == "svg":
        html = f'<img src="data:image/svg+xml;base64,{url_in}" style="max-width:600px;"/>'
    elif filetype == "pdf":
        # Use <embed> or <iframe> for PDF display
        html = (
            f'<embed src="data:application/pdf;base64,{url_in}" '
            'type="application/pdf" width="600" height="600"/>'
        )
    else:
        raise ValueError("filetype must be 'svg' or 'pdf'")
    display(HTML(html))

def make_legend(format_in='svg'):
    legend_url = set_legend_data(format_in=format_in)
    display_legend(legend_url, filetype=format_in)

In [ ]:
make_legend()

data-->
plot_data-->
data_record-->
{
    "archived": null,
    "created": "Tue, 21 Jan 2025 14:22:36 GMT",
    "id": 52,
    "type": "Data",
    "updated": "Tue, 21 Jan 2025 14:22:36 GMT"
}